### ISSUE TITLE
v0.4.0 でデプロイ環境のストレージ容量が小さいとcdk bootstrapに失敗する

### ISSUE THREAD

**Issue by minorun365** [aws-samples/bedrock-claude-chat#106]
Readmeに記載のCodeBuildデプロイ（CloudShell利用）や、CDKデプロイをCloud9で実施すると発生。

権限ないのでPRは出せませんでしたが、 `Readme_ja.md` のWarningに以下文言を記載しておくと良さそうです。

> また、デプロイ時にローカル環境のストレージ容量が不足するとCDKのブートストラップがエラーとなってしまう可能性があります。Cloud9等で実行される場合は、インスタンスのボリュームサイズを拡張のうえデプロイ実施されることをお勧めします。

**Comment by statefb** [comment]
ご報告ありがとうございます！いただいた文言を追加します！

なおPRは主にセキュリティ上の理由により、Fork経由で実施とさせて頂いています（Issueも感謝ですmm）
https://github.com/aws-samples/bedrock-claude-chat/blob/main/CONTRIBUTING.md
