### ISSUE TITLE
Amazon HTTP & WEBSOCKET API Gateway with NONE Authorizer

### ISSUE THREAD

**Issue by vats512** [aws-samples/bedrock-claude-chat#110]
Hey team,

Thanks for the overall project. Super helpful. One thing I wanted to identify path forward for the security risk I am seeing for `Amazon HTTP & WEBSOCKET API Gateway with NONE Authorizer`.

This is the description related to the issue: 
`Your API was flagged because it has insufficient authentication for a specific integration method or route. An API Gateway method is found to have insufficient authentication if it has ‘AuthorizationType’ set to ‘None’.`

1. Can you guide me how to fix this?
2. What's the termination command to stop the service from working? If I want to stop the endpoint deployment, what's the process to follow?

Thanks in advance.

**Comment by statefb** [comment]
Close because this topic must be internal topic.
