### ISSUE TITLE
When creating a bot, if you send multiple files for knowledge, only one will be saved in S3.

### ISSUE THREAD

**Issue by Taikono-Himazin** [aws-samples/bedrock-claude-chat#113]
When creating a bot, if you send multiple files for knowledge, only one will be saved in S3. No errors are displayed.
I sent 8 PDFs, totaling 136MB.
After performing the operation 8 times, all 8 PDFs were registered.
Are there any restrictions, such as only being able to process one large file at a time?
I haven't analyzed the internal structure, but I suspect that the sending from the Client to the server is working fine, but an error occurs when transferring from the server to S3.
If you are transferring directly from the client to S3, then my idea is wrong.

**Comment by statefb** [comment]
I tried to reproduce your issue using multiple pdf files whose sizes are larger than 60MB, but it seems working as I intended.
Could you give me the way to reproduce? Or, we'd appreciate if you could debug what's happening.

The corresponding implementation is bellow.
https://github.com/aws-samples/bedrock-claude-chat/blob/main/backend/app/usecases/bot.py#L83-L95

Thank you in advance.

**Comment by Taikono-Himazin** [comment]
Thanks for the quick comment!
I'll check it again and post it here!

**Comment by Taikono-Himazin** [comment]
Sorry for the late report.
When I tried it, it worked fine until I uploaded it to the S3 folder called _temp, but when I moved it to the documents folder, there seemed to be only one file.
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/25480502/696ec314-b141-46ce-8fe8-fa9f84df64b8)

![image](https://github.com/aws-samples/bedrock-claude-chat/assets/25480502/29c81ab8-76cc-4c2e-beda-49d34731625a)

**Comment by Taikono-Himazin** [comment]
@statefb 
Is there anything you can learn from this information?
If I need more information, what information do I need?

**Comment by Taikono-Himazin** [comment]
fixed by #142
