### ISSUE TITLE
Reduce the Min ACU for Aurora Serverless from 2 to 0.5

### ISSUE THREAD

**Issue by arvehisa** [aws-samples/bedrock-claude-chat#120]
I request to reduce the min ACU for Aurora Serverless from 2 to 0.5.
It would beneficial for users to test the application in most cost-effective configuration.

https://github.com/aws-samples/bedrock-claude-chat/blob/main/cdk/lib/constructs/vectorstore.ts

**Comment by kyosuke-kobayashi-lvgs** [comment]
@statefb 
This issue has already been addressed, so could you please close it?
