### ISSUE TITLE
Can I use Amazon MemoryDB for Redis instead of aurora for vector DB?

### ISSUE THREAD

**Issue by Taikono-Himazin** [aws-samples/bedrock-claude-chat#123]
Using Aurora just for vector searches is too expensive. I think you should use a cheaper service that can only perform vector searches.
When I searched AWS services, it seems that Amazon MemoryDB for Redis has a vector search function.

Can I use Amazon MemoryDB for Redis instead of aurora for vector DB?

**Comment by statefb** [comment]
Aurora serverless is the most cost effective solution.  
see: https://github.com/aws-samples/bedrock-claude-chat/blob/main/docs/RAG.md

we are also planning to integrate with bedrock knowledge base.

Let me close this issue, thank you
