### ISSUE TITLE
How can I develop the WebSocket part locally?

### ISSUE THREAD

**Issue by Taikono-Himazin** [aws-samples/bedrock-claude-chat#127]
The Readme describes how to develop the backend and frontend, but is it possible to run the WebSocket part of the backend locally without using Lambda?
Do I need Docker?

**Comment by statefb** [comment]
Currently we don't support streaming response for local development.
Please use [POST /conversation](https://github.com/aws-samples/bedrock-claude-chat/blob/main/backend/app/route.py#L59-L65) instead.

**Comment by Taikono-Himazin** [comment]
Thank you for answering!
Can I use POST /conversation if stream=false?
