### ISSUE TITLE
Issue when deploying via CloudShell

### ISSUE THREAD

**Issue by tjpatter** [aws-samples/bedrock-claude-chat#138]
I attempted to deploy the project via CloudShell this morning in us-east-1 by following the directions in the README. I received an error on the CloudFormation stack with a "Rollback requested by user." error. I did not attempt to interrupt deployment in any fashion.

<img width="1018" alt="Screenshot 2024-03-07 at 7 54 54 AM" src="https://github.com/aws-samples/bedrock-claude-chat/assets/4923093/ae2c259e-aba7-4b35-be82-21858a7e3ea9">

<img width="1018" alt="Screenshot 2024-03-07 at 7 55 04 AM" src="https://github.com/aws-samples/bedrock-claude-chat/assets/4923093/6d7b3a1d-922a-477a-8c62-a5c7eecabad3">

**Comment by statefb** [comment]
I couldn't reproduce bug.
Did you clone from main branch?

**Comment by tjpatter** [comment]
Closing issue. Today it deployed fine. May have been a transient service issue on AWS' side.
