### ISSUE TITLE
[Feature Request] Use a Bedrock Knowledge Base as RAG source 

### ISSUE THREAD

**Issue by rppth** [aws-samples/bedrock-claude-chat#139]
Can we have an option that integrates with the Bedrock Knowledge base?

**Comment by madtank** [comment]
Good idea, I was thinking Kendra.

**Comment by jeremylatorre** [comment]
Would be also interested by this as I already have a Kendra index as RAG for an other chatbot app

**Comment by statefb** [comment]
Which one is suite for your usecase?
1. Create new data source (Knowledge base)
2. Create new data source (Kendra) 
3. Import from existing one (Knowledge base)
4. Import from existing one (Kendra)

**Comment by statefb** [comment]
1. Create new data source (Knowledge base)

**Comment by statefb** [comment]
2. Create new data source (Kendra)

**Comment by statefb** [comment]
3. Import from existing one (Knowledge base)

**Comment by statefb** [comment]
4. Import from existing one (Kendra)

**Comment by statefb** [comment]
Memo: work on it after RAG chunk reference related issues: #161, #248, #277
