### ISSUE TITLE
[BUG]You cannot star a shared bot unless you have had a conversation with it.

### ISSUE THREAD

**Issue by Taikono-Himazin** [aws-samples/bedrock-claude-chat#144]
# **Describe the bug**
If a shared bot has no conversation history, even if you star it, the star will automatically disappear after a few seconds.

# **To Reproduce**
1. Bot shared for the first time (with no conversation)
2. Click on the star in the top right corner
3. It will go back to starless state after a few seconds.
4. Check the error in developer tools
"Uncaught TypeError: Cannot set properties of undefined (setting 'isPinned')
     at useBot.ts:146:33" is displayed.

I investigated the cause of this and found the following:

①: Stars cannot be attached unless they are in the recentlyUsedBot state.
In the following line of updateSharedBotStarred in useBot.tx, idx becomes -1 and an error will occur in subsequent processing.
````
const idx = recentlyUsedBots?.findIndex((bot) => bot.id === botId) ?? -1;
````

②: recentlyUsedBot searches for LastBotUsedIndex in dynamoDB and automatically creates it from the conversation record. Therefore, it is not possible to add someone to RecentlyUsedBot without having a conversation with them.
Therefore, we believe that it is difficult to change RecentlyUsedBot from the frontend side by any means other than conversation.

# **Expected behavior**
You should be able to star a bot even if you have never spoken to it.

This is because before accessing a URL a friend has given you and having a conversation with them, you might add a star to make it easier to access.

I couldn't come up with a good solution. help me.
thank you.

**Comment by statefb** [comment]
Thank you for reporting the issue. As you mentioned, this sample intends have a conversation before pinning (star). We'll work on it to fix this issue.
