### ISSUE TITLE
[Feature Request]When will you begin implementation of the Admin console ?

### ISSUE THREAD

**Issue by kyosuke-kobayashi-lvgs** [aws-samples/bedrock-claude-chat#159]
**Describe the solution you'd like**

I would like to know when you will start implementing the admin panel. It would be helpful if you could commit even the initial wireframe, so we can begin working on individual customizations.

If you already have a design concept in mind, I would like to help with the implementation.

**Why the solution needed**
A clear and concise description of the reason why you want the solution.

**Additional context**

**Comment by statefb** [comment]
We are working on #124 
We would like to release it by the end of March, but this is not a promise. We would appreciate your understanding.
