### ISSUE TITLE
[Feature Request] Adding prompt template function

### ISSUE THREAD

**Issue by takwad** [aws-samples/bedrock-claude-chat#162]
Is it possible to implement a function that users can create/use prompt templates (filling in predetermined sections of a prewritten text template) similar to Chatbot UI(https://github.com/mckaywrigley/chatbot-ui)?
It would be very convenient for users to utilize LLM.

Thank you for your time and trouble.

**Comment by statefb** [comment]
Please use customized bot feature. If you have any trouble to use it, please re-create a ticket. thank you
