### ISSUE TITLE
[Feature Request]LLM parameter setting from Frontend

### ISSUE THREAD

**Issue by kyosuke-kobayashi-lvgs** [aws-samples/bedrock-claude-chat#166]
**Describe the solution you'd like**
temperature,top_p,top_kが設定できるようにする予定はありますでしょうか？

**Why the solution needed**
A clear and concise description of the reason why you want the solution.

**Additional context**

**Comment by statefb** [comment]
Have you checked following? :
https://github.com/aws-samples/bedrock-claude-chat?tab=readme-ov-file#configure-text-generation--embedding-parameters

**Comment by kyosuke-kobayashi-lvgs** [comment]
ありがとうございます
言葉足らずでしたが、フロントエンド側で任意のBOTに対して指定できるようにしたい、ということでしたmm

**Comment by statefb** [comment]
今の所予定はないですが、実装したい機能の一つですね。
- frontend/src/pages/BotEditPage.tsx
- backend/app/repositories/custom_bot.py
- backend/app/vector_search.py (embeddingのconfも含める)
この辺りに手を入れることで実現はできるかなと思います。やりたくても手が回っていないので、もしご協力いただけるのであれば助かります！

**Comment by kyosuke-kobayashi-lvgs** [comment]
@statefb 
コメントありがとうございます！
やります！

**Comment by statefb** [comment]
@kyosuke-kobayashi-lvgs ありがとうございます、助かります！
一度実装の方針について打ち合わせさせて頂けないでしょうか？恐れ入りますが下記の連絡先まで一度メッセージか何か送っていただけると助かります:
[linkedin](https://www.linkedin.com/in/takehiro-suzuki-430447203/)
[discord](https://discord.gg/VjjpNdhn)

**Comment by kyosuke-kobayashi-lvgs** [comment]
@statefb 
承知しました！
Linkedinアカウント作成して今日の夕方ごろを目処に一度連絡させていただきます！

**Comment by kyosuke-kobayashi-lvgs** [comment]
@statefb 
先ほどLinkedinで繋がり申請させていただきました！

**Comment by kyosuke-kobayashi-lvgs** [comment]
@statefb 
assingedありがとうございます！
すいません、こちら個人アカウントで進めようかなと思っておりましたので、
[2814109](https://github.com/2814109)
こちらのアカウントにアサインいただけますと幸いです！

**Comment by statefb** [comment]
[2814109](https://github.com/2814109)でアサインできなかったので、一旦はそのままにさせてください！（管理上の都合ですみません）

**Comment by kyosuke-kobayashi-lvgs** [comment]
承知しました！
