### ISSUE TITLE
[Feature Request] Support Safari and Edge

### ISSUE THREAD

**Issue by imyoungyang** [aws-samples/bedrock-claude-chat#170]
**Describe the solution you'd like**
If run on Safari, it will get the error: 
Unexpected Application Error!
D.checkVisibility is not a function. (In 'D.checkVisibility()', 'D.checkVisibility' is undefined)

**Why the solution needed**
A clear and concise description of the reason why you want the solution.

**Additional context**

**Comment by kyosuke-kobayashi-lvgs** [comment]
frontend/src/components/ChatListDrawer.tsx

useLayoutEffect内で計算されている箇所が影響していそうです
It seems to be affected by the part of the calculation in useLayoutEffect.

**Comment by kyosuke-kobayashi-lvgs** [comment]
FYI : https://caniuse.com/mdn-api_element_checkvisibility

**Comment by kyosuke-kobayashi-lvgs** [comment]
It seems to be supported in safari 17.4

safari release notes
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes
