### ISSUE TITLE
[BUG] I get a network error when trying to upload PDF to a bot

### ISSUE THREAD

**Issue by fichmann** [aws-samples/bedrock-claude-chat#178]
**Describe the bug**
I get a network error when trying to upload PDF to a bot

**To Reproduce**
1. Go to Bot
2. Click on Create new bot
3. Scroll down to Attachments
4. Select a file to add and press save

**Screenshots**
![Screenshot 2024-03-21 at 09 33 21](https://github.com/aws-samples/bedrock-claude-chat/assets/5448271/9ab2a41e-51aa-4561-a596-44065130645c)

**Additional context**

**Comment by statefb** [comment]
We fixed that problem on #148 . Please try agein using the latest one.
