### ISSUE TITLE
[BUG] Installation failed while running BedrockChatStack CloudFormation template

### ISSUE THREAD

**Issue by soumaghosh** [aws-samples/bedrock-claude-chat#189]
**Describe the bug**
When running the cdk installation from Cloudshell received error during execution of BedrockChatStack CloudFormation template.

**To Reproduce**
1. Executed the commands on Cloudshell -

git clone https://github.com/aws-samples/bedrock-claude-chat.git
cd bedrock-claude-chat
chmod +x bin.sh
./bin.sh

2. Received error - 
Resource of type ‘AWS::Pipes::Pipe’ with identifier ‘EmbeddingPipe1F5BA3-Vr56U5pmFqNE’ did not stabilize. Status Reason is Policy document length breaking Cloudwatch Logs Constraints, either < 1 or > 5120” (RequestToken: f683264a-ec2b-ad4e-e2e6-68fc3931769f, HandlerErrorCode: NotStabilized)

**Screenshots**
<img width="1328" alt="Screenshot 2024-03-25 at 11 09 37 PM" src="https://github.com/aws-samples/bedrock-claude-chat/assets/131231613/880f1187-760d-4364-87a6-a5eb772a5b1f">

**Additional context**

**Comment by statefb** [comment]
Colud you remove stack and re-deploy again?

**Comment by soumaghosh** [comment]
Re-deployed and got the same error.
