### ISSUE TITLE
Feature request: 外部IdentityProviderのサポート

### ISSUE THREAD

**Issue by t-yag** [aws-samples/bedrock-claude-chat#19]
初めまして。
現在Bedrockの組織適応を行なっており、このリポジトリのAppは我々の求めているものに近しく感じています。
こちらはCognitoによるユーザー管理を軸としていますが、外部のIdP連携を実装する予定はありますでしょうか。
(我々はKeycloakを使っており、完全サポートではなくとも実装の余地があると嬉しく思います。)

現時点の実装においてはAuthがcognitoに依存しており、外部IdPによる実装はfrontend, backend, cdkと改修範囲が広く見えます。
ロードマップにない場合は諦めて実装を行いますが、計画にある場合は本リポジトリの改修の流れに乗れると嬉しく思っています。

また外部IdPをサポートしないとしても、cognitoのAuthを必須としない状態へとパラメータ等で制御可能になるだけでも、サンプルプロジェクトとして使いやすくなると感じています。

**Comment by statefb** [comment]
Takumiさん、こんにちは。リクエストありがとうございます。

現在はRAG対応を最優先と考えており、直近では外部IdPに対応する予定は特にありません。

Cognito UserPoolには[外部IdPフェデレーション機能](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation.html)が備わっており、ご活用いただければ大きな改修をせずとも外部IdPと連携することが可能と存じますので、ご検討いただければと思います。またサードパーティ（クラスメソッドさん）製の記事にはなりますが、[こちら](https://dev.classmethod.jp/articles/add-keycloak-to-cognito-with-oidc/)の記事も参考になるかと存じます。プルリクエストは随時歓迎しておりますので、もしコントリビューションいただけたら嬉しいです！

> cognitoのAuthを必須としない状態へとパラメータ等で制御可能になるだけでも

この点については大幅な改修を必要としないので、別途検討させてください（ご意見ありがとうございます）。

お力になれない点、申し訳ございませんが、改めて貴重なご意見ありがとうございました。何卒よろしくお願いいたしますmm

**Comment by wadabee** [comment]
> aws-amplify/ui-react のAuthenticatorコンポーネントを使ってもCognitoの外部IdP連携は可能なのでしょうか？

こちらについては、Cognitoの[Hosted UI](https://docs.aws.amazon.com/ja_jp/cognito/latest/developerguide/cognito-user-pools-app-integration.html) を利用することで連携可能です。

まず、[こちらのコード](https://github.com/aws-samples/bedrock-claude-chat/blob/f46fe72f12dfb73cc0f47850714294673eddd92f/frontend/src/App.tsx#L16)に、oauthの設定をしてください。
[参考：Configuring Amplify Categories](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#scoped-configuration)

```ts
  Amplify.configure({
    Auth: {
     // 省略
      oauth: {
        // Cognitoのドメイン
        domain: 'HostedUIのドメイン(***.auth.ap-northeast-1.amazoncognito.com)',
        scope: ['openid'],
        // アプリケーションのURL
        redirectSignIn: 'http://localhost:3000/',
        redirectSignOut: 'http://localhost:3000/',
        responseType: 'code',
      },
    },
  });
```

フロントエンドのプログラムで、`Auth.federatedSignIn()` を実行することで、HostUI にリダイレクトされ認証を行うことが可能になります。
[このページのサンプルコード](https://docs.amplify.aws/lib/auth/social/q/platform/js/#deploying-to-amplify-console)が参考になるかと思います。

> IAM Identity Centerとの連動なども是非検討いただけると嬉しく思います。

貴重なご意見ありがとうございます！検討させていただきます！

**Comment by t-yag** [comment]
> こちらについては、Cognitoの[Hosted UI](https://docs.aws.amazon.com/ja_jp/cognito/latest/developerguide/cognito-user-pools-app-integration.html) を利用することで連携可能です。

なるほど、ありがとうございます。こちらで実装してみようと思います。

ご回答いただいた内容で本件はクローズとさせていただきます。
引き続きBedrock及び本リポジトリが発展することを心待ちにしております！
