### ISSUE TITLE
[BUG] No Automatic Title for Conversations

### ISSUE THREAD

**Issue by AdityaIndoori** [aws-samples/bedrock-claude-chat#194]
**Describe the bug**
New conversations for Claude3 default/specialized bots do not create an automatic titles for the conversations. Instead all the conversations are named as "New conversation".

**To Reproduce**
1. Go to New Chat
2. Select a Claude 3 model (Haiku or Sonnet)
3. Begin chatting
4. Look at the Chat title in the History section of the left pane
5. The title of the chat is "New Conversation"

**Screenshots**
![Screenshot Claude ChatBot Conversation Title Bug](https://github.com/aws-samples/bedrock-claude-chat/assets/16860249/78207623-7cc8-465e-8e0e-1fc9d9ba46e6)

**Comment by jeremylatorre** [comment]
This is because you need to enable Claude 3 Haiku in your aws account > Model Access

**Comment by AdityaIndoori** [comment]
Hey, that kinda fixed the issue. Thank you for suggesting it. However, now I'm seeing another issue where the title is sometimes in English and sometimes in another language. Is that a bug?

![Screenshot_20240327_112925_Chrome](https://github.com/aws-samples/bedrock-claude-chat/assets/16860249/ab71e88d-cd34-4686-9c74-ffc7e9a15da7)

**Comment by statefb** [comment]
We specify the language here:
https://github.com/aws-samples/bedrock-claude-chat/blob/main/backend/app/usecases/chat.py#L322

It's a issue comes from prompt-engineering or LLM model. The original problem looks like solved, so close this issue. Thank you @jeremylatorre
