### ISSUE TITLE
[BUG] Incorrect Header Title on Small Screens

### ISSUE THREAD

**Issue by wadabee** [aws-samples/bedrock-claude-chat#196]
**Describe the bug**
In the case of small screens, the header is displayed, but the header title always shows "New Conversation" regardless of the current screen or context. The header content should be dynamic and change based on the specific screen or view being displayed.

**To Reproduce**

**Screenshots**
<img width="859" alt="image" src="https://github.com/aws-samples/bedrock-claude-chat/assets/52243855/78a51858-cf3f-4b0a-8c3d-6fa5eb4adc54">

**Additional context**

**Comment by k70suK3-k06a7ash1** [comment]
conversations?.find((c) => c.id === conversationId)?.title ?? 'New Chat'


frontend/src/hooks/useConversation.ts
