### ISSUE TITLE
[Feature Request] PDF/Document upload directly on chat window

### ISSUE THREAD

**Issue by statefb** [aws-samples/bedrock-claude-chat#198]
**Describe the solution you'd like**
Enables uploading doc directly on chat input window
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/ec324264-d8cb-4b7e-bb68-bec9f71f08ac)

**Why the solution needed**
For ad-hoc querying

**Additional context**

**Comment by jeremylatorre** [comment]
We'll probably need to work on this feature within next weeks. Did you have any lead about this feature?
Parsing in frontend/Backend? Add the content in the pre-prompt inside <document></document> tags?

**Comment by statefb** [comment]
> Did you have any lead about this feature?
No. We are also considering implementing it, but there is an issue with parsing documents. The unstructured package in Python is the de facto standard, but the package size is large, and when implemented in Lambda, a phenomenon has been observed where cold starts degrade to around 10 seconds. Additionally, since unstructured writes to areas other than /tmp, it is not practical from this perspective either. We need to explore a cost-effective method while maintaining the UX.

**Comment by dezhouc2** [comment]
> > Did you have any lead about this feature?
> 
> No. We are also considering implementing it, but there is an issue with parsing documents. The unstructured package in Python is the de facto standard, but the package size is large, and when implemented in Lambda, a phenomenon has been observed where cold starts degrade to around 10 seconds. Additionally, since unstructured writes to areas other than /tmp, it is not practical from this perspective either. We need to explore a cost-effective method while maintaining the UX.

By the way, I'm wondering what is the maximum capability for loading files for each console bot? thank you

**Comment by statefb** [comment]
Possible solution: using converse API
