### ISSUE TITLE
[BUG] Updating to latest version, cloudFormation failed update

### ISSUE THREAD

**Issue by jeremylatorre** [aws-samples/bedrock-claude-chat#206]
**Describe the bug**
The stack named BedrockChatStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Resource  must be in ARN format or "*". (Service: Iam, Status Code: 400,

**To Reproduce**
Pulled the latests commits to update my stack, then run:
cdk deploy --require-approval never --all

 to update my existing stack ( I already have several bot exisitng with knowledge so I can't remove everything and restart from scratch

**Additional context**

**Comment by statefb** [comment]
Could you send more CFn logs?

**Comment by jeremylatorre** [comment]
It seems to be related to BackendApi > HandlerRole > Default Policy

**Comment by jeremylatorre** [comment]
I can bypass the issue by setting  "enableUsageAnalysis": true instead of false

**Comment by jeremylatorre** [comment]
Found the issue:


~~~~~~
      {
        "Action": [
          "athena:GetDataCatalog",
          "athena:GetQueryExecution",
          "athena:GetQueryResults",
          "athena:GetWorkGroup",
          "athena:StartQueryExecution",
          "athena:StopQueryExecution",
          "glue:GetDatabase",
          "glue:GetDatabases",
          "glue:GetPartition",
          "glue:GetPartitions",
          "glue:GetTable",
          "glue:GetTables"
        ],
        "Resource": "",             <------ HERE: Empty, must be ARN or “*”
        "Effect": "Allow"
      },
~~~~~~~

This shoud not be triggered when we disable UsageAnalysis

**Comment by statefb** [comment]
Which version are you using? Currently the `usageAnalysis` is true by default and not be intended to set to false. In the near future, we'll remove that parameter from cdk.json.

**Comment by jeremylatorre** [comment]
I just put myself to false because I don't need it for now

**Comment by statefb** [comment]
If set to true and still problem remains, create another issue.
