### ISSUE TITLE
[Feature Request]: translate readme into chinese

### ISSUE THREAD

**Issue by end-cycle** [aws-samples/bedrock-claude-chat#207]
**Describe the solution you'd like**

I see this [issue](https://github.com/aws-samples/bedrock-claude-chat/issues/41#issuecomment-1728815870) saying that it is necessary to translate readme doc, but I don't see pr. Do you have any plans to update the documentation? Maybe I can help update the Chinese translation.

**Why the solution needed**

Translation support

**Additional context**

![image](https://github.com/aws-samples/bedrock-claude-chat/assets/62703840/7ea2a888-53f5-4a06-8ecf-a68cdd159afe)

**Comment by statefb** [comment]
Thank you for your willingness for i18n support.
- If you can, we'd be glad if you could improve [i18n/zh/index.ts](https://github.com/aws-samples/bedrock-claude-chat/blob/main/frontend/src/i18n/zh/index.ts).
- The content of the README may change in the future, and whenever the English version is updated, the Chinese version will also need to be updated. It might be more appropriate to set up an automated translation workflow using GitHub Actions.

**Comment by end-cycle** [comment]
OK👌，I understand，i will review the (i18n/zh/index.ts)[i18n/zh/index.ts](https://github.com/aws-samples/bedrock-claude-chat/blob/main/frontend/src/i18n/zh/index.ts) in the near future。
