### ISSUE TITLE
[BUG] MD file extension is missing

### ISSUE THREAD

**Issue by jeremylatorre** [aws-samples/bedrock-claude-chat#210]
**Describe the bug**
I tried to upoad an MD file in knowledge base and got the error wihile syncing

Knowledge Sync Error
An error occurred while synchronizing Knowledge. Please check the following message:
partition_md is not available. Install the md dependencies with pip install "unstructured[md]"

**To Reproduce**
1. Create or update a bot
2. Upload a .md file
3. Edit bot

**Comment by statefb** [comment]
After updating still have the same issue, create another issue. thank you
