### ISSUE TITLE
[BUG]Failed to invoke bedrock

### ISSUE THREAD

**Issue by jeremylatorre** [aws-samples/bedrock-claude-chat#212]
**Describe the bug**
Trying to have a conversation following big latest update on code

I have added a console log on message.data to understand what's inside.
Failed to invoke bedrock. [usePostMessageStreaming.ts:74:20]
(http://localhost:5173/src/hooks/usePostMessageStreaming.ts)

Tried to modify the ws endpoint to see how it behaves but I have an error earlier in the process telling that he can't reach WS endpoint. So it's really seems to be a problem between WS and Bedrock connection.

**Additional context**

**Comment by statefb** [comment]
Cloud you describe reproduction step with clear explanation?

**Comment by jeremylatorre** [comment]
I'm closing this issue since I cannot reproduce this bug anymore
