### ISSUE TITLE
[Feature Request] Set shutdown time to stop RDS

### ISSUE THREAD

**Issue by k70suK3-k06a7ash1** [aws-samples/bedrock-claude-chat#214]
**Describe the solution you'd like**
任意の時間帯（夜間など）を指定して、指定した時間帯にRDSを停止し、インフラコストが削減できるように管理画面で設定できるようにしたいです

**Why the solution needed**
A clear and concise description of the reason why you want the solution.

**Additional context**

実装やりたいです！

**Comment by statefb** [comment]
ありがとうございます！cdk.jsonに追記できるようにする方法でも良いかと思いましたが、管理画面のUI上から実施されたい感じでしょうか？？

**Comment by 2814109** [comment]
当初イメージしてたのは後者のイメージでした！
ただ、確かにCDK追記でもいいような気もしてきました・・・（頻度高く停止したい時間帯がコロコロ変わるか、と言われると難しいところです・・・）

**Comment by statefb** [comment]
管理者用の画面はあった方が利便性が上がることもあるかと思いますので、何か他に用途があれば実装するのも良いと思っています。ただ頂いたこのFRの場合、cdk.jsonで十分かなとは思います。
@wadabee どう思われますか？

**Comment by wadabee** [comment]
コスト低減は永遠のテーマだと思うので、何らかの形で取り込みたいですね！
停止時間は頻繁に変更するものではないと思うので、一旦cdk.jsonによる設定でいいと思います。
画面から変更できた方がユーザーフレンドリーではありますが、実装コストに見合ったリターンはなさそうかなという印象です（その分、他のFRを消化した方が良さそう）

**Comment by 2814109** [comment]
@statefb  @wadabee 
お二人とも、ご意見ありがとうございますmm

cdk.jsonでの実装方針、私も納得しました！
