### ISSUE TITLE
[BUG] Missing API

### ISSUE THREAD

**Issue by usc196196** [aws-samples/bedrock-claude-chat#239]
Deploy using CDK successfully, but login to frontend, no APIs there.

![img1](https://github.com/aws-samples/bedrock-claude-chat/assets/35538464/65bf33e7-832f-48be-84dc-5a35dffc1d3b)

**Comment by statefb** [comment]
Need to publish. Please see:  
https://github.com/aws-samples/bedrock-claude-chat/blob/main/docs/PUBLISH_API.md

**Comment by usc196196** [comment]
Sorry I am not quite understand which part is being wrong.

![image](https://github.com/aws-samples/bedrock-claude-chat/assets/35538464/188cb0d6-f29d-4f50-84e1-3cbb69873171)

Published the API, but still not able to start conversation. How could I figure out the issue?
