### ISSUE TITLE
[Feature Request] Turn the returning of related documents off/on for a bot

### ISSUE THREAD

**Issue by DTheunis** [aws-samples/bedrock-claude-chat#248]
## Describe the solution you'd like

A way of turning off the feature of a bot returning related documents in it's response. Customizable per bot.

## Why the solution needed

Some bots (which are shared) should not be able to return documents to users.

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by statefb** [comment]
When turned off, should it disable both the chunk content and the reference links? (React with thumbs up /down)
