### ISSUE TITLE
[Feature Request]I want to upgrade the version of react-markdown.

### ISSUE THREAD

**Issue by Taikono-Himazin** [aws-samples/bedrock-claude-chat#261]
I would like to use rehype-katex or remark-math.
To do so, it seems that you need to increase the version of react-markdown to ^9.0.0.
I have the ^9.0.0 update on hand.
I forget what the reason was (which plugin I introduced made it necessary to raise it to 9), but is it possible to make a change like this?

**Comment by Taikono-Himazin** [comment]
marge #262

**Comment by Taikono-Himazin** [comment]
I mistakenly closed a pull request and an issue.
We will open again.

**Comment by Taikono-Himazin** [comment]
@statefb 
I want to display TeX, Code, Link, etc. in addition to MarkDown.
I would like to be able to display something like this image.
<img width="520" alt="image" src="https://github.com/aws-samples/bedrock-claude-chat/assets/25480502/a31c0a37-ca92-442f-8a32-4a6da2471c07">


For that purpose, I would like to add remarkPlugins and rehypePlugins.
But I needed ReactMarkdown to be 9.x.x.
This is an update for that purpose.

**Comment by Taikono-Himazin** [comment]
I was saying the wrong thing.
I didn't need to upgrade react-markdown.

I also changed the PR because I was having performance issues when I upgraded.

**Comment by statefb** [comment]
Can we close this issue?

**Comment by Taikono-Himazin** [comment]
Yes!
Thank you.
