### ISSUE TITLE
[BUG] POST /conversation/related-documents 500 in local

### ISSUE THREAD

**Issue by ClementVanPeuter** [aws-samples/bedrock-claude-chat#270]
## Describe the bug

In local development the POST  /conversation/related-documents route throw a 500 , in the local UI, ( like a timeout or so) even having filled in the env variables ( DB_NAME, DB_USER, DB_PASSWORD, DB_PORT). Am I missing something about this ?

## To Reproduce

Set all the env var according to the local development backend and frontend Readme.  
`VITE_APP_API_ENDPOINT` pointing on the local python backend.
And exporting all the env vars according to the backend local dev README +  DB_NAME, DB_USER, DB_PASSWORD, DB_PORT.  
Backend is plug to AWS services and nothing in local ( Nor Docker, Postgres or anything) pointing straight out to AWS services.

1.Launch local UI.
2.Ask a question ( for a RAG answer)
Network console show a 500 on the /conversation/related-documents route

```
Can't create a connection to host xxxxxxxxxxxxxx and port xxxxxxxx( timeout is None and Source address is None)
```

**Comment by statefb** [comment]
Because the aurora database is on the private subnets, which is not allowed to access from outside of the vpc.
To test functionality related to aurora, we need to add bastion as a proxy.

**Comment by ClementVanPeuter** [comment]
@statefb Thank you for the explanation.

**Comment by statefb** [comment]
@ClementVanPeuter Your welcome, let me close the issue

**Comment by wiselancer** [comment]
Hey guys, I'm having the same issue for production. Can anyone suggest the fix? thanks

<img width="1477" alt="Screenshot 2024-10-29 at 1 30 35 PM" src="https://github.com/user-attachments/assets/bba79d05-b893-428f-a6d2-c8e9b9664833">

<img width="1472" alt="Screenshot 2024-10-29 at 1 32 32 PM" src="https://github.com/user-attachments/assets/339200cf-7814-4d7e-b52d-ddee3a23e083">
