### ISSUE TITLE
[Feature Request]Add LLM Agent

### ISSUE THREAD

**Issue by k70suK3-k06a7ash1** [aws-samples/bedrock-claude-chat#274]
## Describe the solution you'd like
LLM Agentを追加します
https://github.com/aws-samples/bedrock-claude-chat/pull/241

See : https://docs.anthropic.com/claude/docs/tool-use

## Why the solution needed

A clear and concise description of the reason why you want the solution.

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by statefb** [comment]
Impementation guide:

### Rendering
- Do not display the details of the thought process on the FE
- Display the progress in the form of a progress bar
  - It might be good to display the tools being used
- Send the full text from the BE
- No streaming
### Tools
- Default is search only (?)
- Contribute to app/agents/tools/examples
  - Initially, get weather, stock prices, etc.
  - Developers need to write scripts themselves and have them cdk deploy
- Scan the tools in a directory like app/agents/tools/prod and return them to the FE
  - On the bot creation screen, the FE can turn the toggle switch ON/OFF
  - While there is no explicit RAG switch, if any switch is ON and Knowledge exists, it will automatically be used as a tool (let the LLM consider it)

**Comment by tomaszdudek7** [comment]
@statefb - I suppose the most requested tool would be using external search engine (when necessary to answer a given question). I see it is set up as "planned" - what does it mean?

**Comment by statefb** [comment]
@tomaszdudek7 Yes I agree with you. But almost search engine api e.g. google search API requires secret values, which makes the deployment procedure complex. I'll add a guidance how to setup own tool on this project. It will be released by the end of June.

**Comment by k70suK3-k06a7ash1** [comment]
@statefb 
こちらCloseしておきます！（FE,BEがMergeされた為）
