### ISSUE TITLE
[Feature Request] Add related document on history messages

### ISSUE THREAD

**Issue by ClementVanPeuter** [aws-samples/bedrock-claude-chat#277]
## Describe the solution you'd like

Currently, in RAG mode if you chat with the chatbot it will return related documents in context form in the chat. We can open a modal with the concerned context.

But, in history, we cannot open modal to the related documents or context, because related documents are generated and send only on the 'sendChat' event.  

## Why the solution needed

We want to be able to consult references and related documents to conversations in history, because it's more convenient than chatting again.

## Additional context
I only scratch the surface about code,I think I understand that in the conversation db there are no link to the related documents.

I'm really a noob in the AWS ecosystem and CDK is really unknown for me :/

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes but I can't implement this by myself, my knowledge on the backend and AWS architecture is too thin.

**Comment by statefb** [comment]
We are going to work on it. Thanks
