### ISSUE TITLE
[Feature Request] Add Italian Language

### ISSUE THREAD

**Issue by angelo-malatacca** [aws-samples/bedrock-claude-chat#278]
## Describe the solution you'd like

As I'm an Italian native speaker, I would like to add the Italian language translations (i18n).

## Why the solution needed

It can be beneficial for people who speaks Italian and therefore increase possible users

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [ X] Yes
- [ ] No

**Comment by statefb** [comment]
Thank you for your suggestion! Could you please create a PR? #258 can be a referene.
