### ISSUE TITLE
[BUG] - unable to run claude models in us-west-2

### ISSUE THREAD

**Issue by tnh** [aws-samples/bedrock-claude-chat#286]
## Describe the bug

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

## To Reproduce

* setting AWS_DEFAULT_REGION=us-east-2 
* closing repo
* running `./bin.sh`

Then I was unable to access any model - and would see the following
<img width="1408" alt="Screenshot 2024-04-29 at 8 47 52 am" src="https://github.com/aws-samples/bedrock-claude-chat/assets/716595/217288e4-3857-4a37-af43-73c727e7281c">

I have access to all the models in the us-east-2 region:

<img width="1493" alt="Screenshot 2024-04-29 at 8 46 09 am" src="https://github.com/aws-samples/bedrock-claude-chat/assets/716595/63c48b80-fd2e-4f72-b9a8-8c91c21bb2e4">
<img width="1233" alt="Screenshot 2024-04-29 at 8 46 59 am" src="https://github.com/aws-samples/bedrock-claude-chat/assets/716595/1127802d-62ce-44f8-a037-91ba13f8a6ae">

the model id does seem like the same model id:

<img width="1443" alt="Screenshot 2024-04-29 at 8 47 32 am" src="https://github.com/aws-samples/bedrock-claude-chat/assets/716595/28632921-dc23-41aa-9238-ed904d0af619">

I see the following two log messsages in the cloudwatch logs for the Websocket Lambda:

<img width="1308" alt="Screenshot 2024-04-29 at 8 45 16 am" src="https://github.com/aws-samples/bedrock-claude-chat/assets/716595/73b62d05-5ab9-4243-be4c-59d7b1fff381">
<img width="1316" alt="Screenshot 2024-04-29 at 8 44 59 am" src="https://github.com/aws-samples/bedrock-claude-chat/assets/716595/66de06f5-2553-4eb6-b653-fa0bd9804093">

This is the message in the browser on the client side of the WSS call:

```
"{\"conversationId\":\"01HWKDG43PGTFQNRP1Y9WK45TM\",\"message\":{\"content\":[{\"body\":\"test\",\"contentType\":\"text\"}],\"model\":\"claude-v3-opus\",\"role\":\"user\",\"feedback\":null,\"parentMessageId\":\"system\"},\"token\":\"eyJraWQiOiJzY2k0aWMxUXZEVTEwU2lUM2gyRnNUZ1dBTVM5ZlNsVFErK0g3cUlcL21GND0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI3OGIxMjNmMC1lMDkxLTcwNTAtZTIxOC01OWRhNTMzZWFhZmUiLCJjb2duaXRvOmdyb3VwcyI6WyJBZG1pbiIsIlB1Ymxpc2hBbGxvd2VkIl0sImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtd2VzdC0yLmFtYXpvbmF3cy5jb21cL3VzLXdlc3QtMl9DbzcxbUpzSXAiLCJjb2duaXRvOnVzZXJuYW1lIjoiNzhiMTIzZjAtZTA5MS03MDUwLWUyMTgtNTlkYTUzM2VhYWZlIiwib3JpZ2luX2p0aSI6ImYwNGM2ZmYwLTY5YTItNGQxOC1hMDdmLTIwYmQ2MjlkYTExNyIsImF1ZCI6IjZwaDZ0Z3RrZjQ1a3I5Mm0xOG85dHNxbGwiLCJldmVudF9pZCI6ImUzOGVjNDZkLWE5MTUtNDA5YS04YmRkLTZiNTViNjc4ODQ1YyIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzE0MjA0MzEwLCJleHAiOjE3MTQ0MjkzODQsImlhdCI6MTcxNDM0Mjk4NCwianRpIjoiMDQzOWI3NGEtNDEyMS00ZWZjLThhY2YtZTk4ZmM1MTljNGY2IiwiZW1haWwiOiJ0aG9ybmlicm9va0BzZWVrLmNvbS5hdSJ9.BPwjF8w8M0PAAnZa-wg0SVAaXWM1RcPuznv4gbzy6AA-OAoFb14X-i27vYiKaLdkzRzBAb2KTCIs1h50BBirz5bbR41q_cikjBw5tpReaj78XyvVhwvDVWd7DiwjwbPYx_vWw-qTiC8vmKXvTWDRq86WYduJO9ny6oyyHUqbkaIeNJqT2VQ7Yitflw___FoTQIaqvH27hj17HJjUCXuLn_MljeEHgUaYP7x7tbfisQt5DGxa35PQ66fvvSHlirDlHOGtWFw2DdbG07L1l0XcfDZAVlM9_PYv0ppiuNpUGXT6Q5t0axx4Jc354OBUWKgNS5txyELOAfRr2HH_MTZwdw\"}"

```

**Comment by statefb** [comment]
Could you please let me know Sonnet / Haiku are available?

**Comment by prometheusresearchlabs-partha** [comment]
Hello, I have the exact same error as tnh, and to confirm, I also have Haiku and Sonnet enabled, these are working fine in the Chat, Opus is not and is showing the same error as above, if you require any further context, please let me know

**Comment by statefb** [comment]
Have both of you modified `bedrockRegion`?  
ref: https://github.com/aws-samples/bedrock-claude-chat#deploy-using-cdk

**Comment by prometheusresearchlabs-partha** [comment]
Yes, Claude 3 Opus is only available in Oregon hence bedrockRegion is set to us-west-2 in cdk.json, I also tried again and replaced any instance of us-east-1 to us-west-2 and still have this error. Also tried in multiple AWS accounts just in case
