### ISSUE TITLE
[BUG] Slow retrieval of documents

### ISSUE THREAD

**Issue by jeremylatorre** [aws-samples/bedrock-claude-chat#305]
## Describe the bug

When using RAG, I noticed that performances where very low when trying to retrieve information from documents.
Any lead about what is causing this. Clearly the difference between rag and standard bot is huge at that time.
It might also depend on number of documents.

**Comment by statefb** [comment]
Could you provide the detail? Please do not ignore the issue template.

**Comment by jeremylatorre** [comment]
When I use my bot, it takes sometimes 17s before starting to render the content.

The first step [Retrieve Knowledge] looks ok, but after that, cursor stay at the beginning of the line for a very long time before starting to write the response.

This doesn't happen when using the LLM without documents, and it seems to increase with the number of document in the knowledge base.

**Comment by statefb** [comment]
Could you check the items in postgres? We can use management console to query and the table definition can be reffered [here](https://github.com/aws-samples/bedrock-claude-chat/blob/main/cdk/custom-resources/setup-pgvector/index.js#L11-L28).

**Comment by jeremylatorre** [comment]
Could it be related to the instantion of a Lambda function? The behavior only appear on the first inference for a new conversation

**Comment by statefb** [comment]
Have you forked and customized this sample? Large container causes longer cold start. You can check whether the invocation is cold or not by reffering cloudwatch logs.  
https://stackoverflow.com/questions/47061146/how-can-i-detect-cold-starts-in-aws-lambda

**Comment by jeremylatorre** [comment]
Ok I have digged a llittle bit on the logs and I found that the POST call to related-documents is very long by itself:

Request POST /conversation/related-documents (15:15:32 - 15:15:44)
Duration : 11697 ms

I'm not currently up to date with the codebase and we will perform a full update soon. I'll keep you updated on this.

**Comment by statefb** [comment]
@jeremylatorre Thank you for the update. The query part to postgres seems to making the very long latency. For the cost effectiveness, the ACU configured at minimum value by default. Choosing larger value might solve the problem .
