### ISSUE TITLE
[Feature Request] Extend Playwright Timeout to Prevent Synchronization Errors

### ISSUE THREAD

**Issue by ksk-17090k1** [aws-samples/bedrock-claude-chat#306]
## Describe the solution you'd like

I'd like to be able to register websites that take a long time to load as knowledge.

## Why the solution needed

If you register a URL that takes a long time to load (for example, https://www.value-domain.com/media/sidejob-home/) on the bot settings screen, a synchronization error occurs due to a timeout in Playwright.

## Implementation feasibility

The default timeout value for Playwright `Page` is [30000 milliseconds](https://playwright.dev/python/docs/api/class-page#page-goto-option-timeout).
To avoid timeout errors, you can consider extending this period.

[backend/embedding/loaders/playwright.py]
```python
response = page.goto(url)
page.set_default_timeout(300000)
```

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by statefb** [comment]
I believe that almost all of websites can be rendered within 30 sec ([blog](https://blog.hubspot.com/marketing/page-load-time-conversion-rates)), and 5 min (300 sec) is too long for the default value. Do you have any statistics of the duration for the website you want to handle?

**Comment by inagaki-keisuke-lvgs** [comment]
thank you for your feedback!
As you mentioned, sites that take more than 30 seconds to load are likely having some problems.
If you expect an error when setting such a site in the bot's configuration, it seems there is no need for further modifications.

**Comment by statefb** [comment]
If there are no downsides, it may also be worth considering extending the default timeout as well.

**Comment by ksk-17090k1** [comment]
Unfortunately, I couldn't find any statistical data that would help determine how long to extend the timeout value.
Your concerns about performance are reasonable, so I agree that we should handle the timeout value in a forked repository. 
I think it's fine to close this issue :)
