### ISSUE TITLE
[Feature Request] Customize max_results during chat

### ISSUE THREAD

**Issue by DTheunis** [aws-samples/bedrock-claude-chat#313]
## Describe the solution you'd like
An input box so we can customize the max_results variable to search results in the db.

## Why the solution needed
Sometimes we would like to have more results returned from the Database than the predefined value (or less), we would like to be able to control this.

## Additional context
/

## Implementation feasibility
Done 

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by statefb** [comment]
PR is under the review on #303. let me close this issue
