### ISSUE TITLE
[Feature Request] bot knowledge resync

### ISSUE THREAD

**Issue by byongwu** [aws-samples/bedrock-claude-chat#317]
## Describe the solution you'd like

A button to resync the given knowledge URL.

## Why the solution needed

Otherwise, we will need to create a new bot with the new URL.
It will cause users to change the bot.

## Additional context

None.

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?
- [X] Yes
- [ ] No

**Comment by statefb** [comment]
Open edit screen by pushing `Edit` button and then just click `Edit` button at the bottom of the screen.
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/8dbbb09b-7150-4374-a811-33e033800307)
