### ISSUE TITLE
[BUG] An error occurred while responding behind proxy

### ISSUE THREAD

**Issue by tis-abe-akira** [aws-samples/bedrock-claude-chat#332]
## Describe the bug

To limit access from within the company, we are using a PROXY server for access. Because of this, when sending prompts from the chat, we frequently encounter the message "An error occurred while responding." After pressing ”Resend”, it works normally. 
Therefore, while chat usage is possible, but, we consider this to have significant usability issues.

If this can be improved through configuration settings, please let us know. Ideally, we hope for an improvement.

## To Reproduce

1. Enter the prompt.
2. Press the Enter key to submit the request.
3. The following error occurs quite frequently in the screenshots.
4. Pressing the "Resend" button results in a normal response.

## Screenshots
![bedrock_claude_chat_issue](https://github.com/aws-samples/bedrock-claude-chat/assets/129920148/8bae5704-75ce-4752-b7d8-22fcccca8162)

## Additional context

N/A

**Comment by statefb** [comment]
Thank you for reporting this issue. Have you checked log yet? If not, could you take a trouble to find abnormal behavior? The name of log looks like: /aws/lambda/BedrockChatStack-WebSocketHandlerXXXX

**Comment by tis-abe-akira** [comment]
Thank you for your reply.
To be honest, your response allowed me to locate the logs.
When I checked the logs, there were no ERROR level log entries, only INFO level ones at the time this issue occurred.

I don't understand which part of the logs I should send to help resolve the issue. Could you please advise me?

**Comment by tis-abe-akira** [comment]
The following errors are occurring when viewed through the Developer Tool in WebBrowser (FireFox):

1. 
Could not establish a connection to the server at wss://xxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev.

2.
```
error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: null
defaultPrevented: false
eventPhase: 0
explicitOriginalTarget: WebSocket { url: "wss://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev", readyState: 3, bufferedAmount: 0, … }
isTrusted: true
originalTarget: WebSocket { url: "wss://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev", readyState: 3, bufferedAmount: 0, … }
returnValue: true
srcElement: WebSocket { url: "wss://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev", readyState: 3, bufferedAmount: 0, … }
target: WebSocket { url: "wss://xxxxxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev", readyState: 3, bufferedAmount: 0, … }
timeStamp: 190673083
type: "error"
<get isTrusted()>: function isTrusted()
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
```
I hope this information will be helpful.

**Comment by statefb** [comment]
Thank you for the detail. Could you check your corporate proxy setting? It likely block the webscoket connection.

**Comment by tis-abe-akira** [comment]
Understood. It seems likely that the issue is caused by our company's proxy. In practice, since it responds correctly upon retransmission, it's a bit inconvenient but not a major problem for practical use. If this is an issue specific to our environment, I think it would be acceptable to close it.
