### ISSUE TITLE
[BUG] Question format

### ISSUE THREAD

**Issue by joopdo** [aws-samples/bedrock-claude-chat#338]
Running bin.sh gives "Are you a new user or already using v1.x of Bedrock Claude Chat? (y/N):  "

The 'or' format of the question makes a Y/N answer confusing.

**Comment by statefb** [comment]
Thank you for pointing out! Could you take a trouble to make a pull request?

**Comment by k70suK3-k06a7ash1** [comment]
@joopdo 
Do you feel it would be easier to understand if the decision is whether or not the User is using V0.x?

If you want, I can create a PR for you.

**Comment by k70suK3-k06a7ash1** [comment]
@joopdo 
like this
https://github.com/aws-samples/bedrock-claude-chat/pull/375

please check it

**Comment by joopdo** [comment]
Thanks @k70suK3-k06a7ash1 ! Much appreciated
