### ISSUE TITLE
[Bug] Timeout Occurs in Embedding When Adding a Large Number of URLs to Knowledge

### ISSUE THREAD

**Issue by edamame8888** [aws-samples/bedrock-claude-chat#341]
## Describe the bug

When creating a bot, inputting about 100 URLs (not YouTube URLs) results in the following error in BedrockChatStack-EmbeddingTask:

```txt
ERROR:embedding.loaders.playwright:Error fetching or processing https://***, exception: Timeout 30000ms exceeded.
```

version: v1

## To Reproduce

- **Prerequisites**
  - User must be a member of the Admin group(cognito).
- **Steps to Reproduce**
  1. Click "Bot Console" from the menu.
  2. Click the "Create New Bot" button.
  3. Enter "BugBot" in the Name field, and input about 100 URLs in the URL input form.
  4. Click the "Create" button.
- **How to Verify the Issue**
  1. Navigate to CloudWatch BedrockChatStack-EmbeddingTaskLogGroup*** and confirm that the error "ERROR:embedding.loaders.playwright:Error fetching or processing https://***, exception: Timeout 30000ms exceeded." has occurred.

## Screenshots

<img width="1170" alt="BedrockChatStack-EmbeddingTaskLog" src="https://github.com/aws-samples/bedrock-claude-chat/assets/41494250/b147c0b0-5c63-4dd4-ba1a-ff6bae7b7444">

<img width="1351" alt="スクリーンショット 2024-06-05 9 05 18" src="https://github.com/aws-samples/bedrock-claude-chat/assets/41494250/aedcc0c7-27d1-4b6e-a563-976e5e9107e7">

### Workaround Tried

I confirmed an improvement by calling page.close() within a loop of playwright on my end.

https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/embedding/loaders/playwright.py#L150-L170

```diff
            for url in self.urls:
                try:
                    page = browser.new_page()
                    response = page.goto(url)
                    if response is None:
                        raise ValueError(
                            f"page.goto() returned None for url {url}")

                    text = self.evaluator.evaluate(page, browser, response)
                    metadata = {"source": url}
                    docs.append(Document(page_content=text, metadata=metadata))
+                    page.close()
+                    logger.info(f"Loaded {url} and page closed.")
                except Exception as e:
                    if self.continue_on_failure:
                        logger.error(
                            f"Error fetching or processing {url}, exception: {e}"
                        )
                    else:
                        raise e
            browser.close()
        return docs
```

#### Result 

<img width="1396" alt="success-embedding-log" src="https://github.com/aws-samples/bedrock-claude-chat/assets/41494250/d41a50e3-cda1-42de-b6f1-1cd8d4ec4667">

**Comment by statefb** [comment]
Thank you for suggesting workaround! Could you guess why your solution resolve the timeout issue?

**Comment by edamame8888** [comment]
OK! I'll respond after work, so please wait a bit.

**Comment by edamame8888** [comment]
## Performance Before & After

> Could you explain or guess why your solution resolve the timeout issue?

The memory being maxed out at 100% is the cause.

Before the improvement, the memory performance in Cloud Watch Insight was maxed out and the content retrieval never finished.
After the improvement, memory performance improved and we confirmed that the embedding was completed in a short period of time.

<img width="992" alt="スクリーンショット 2024-06-06 7 40 26" src="https://github.com/aws-samples/bedrock-claude-chat/assets/41494250/028eeee5-daf6-4960-a09d-8dadabce21ed">
