### ISSUE TITLE
[BUG] Error when trying to publish the api

### ISSUE THREAD

**Issue by PolicarpoDi** [aws-samples/bedrock-claude-chat#344]
## Describe the bug

After I started using v1, I can't publish the API. I always get the error message (I'm using the us-east-1 region). Before, I was using v0 and the us-west-2 region, and I had managed to publish.

## To Reproduce

1. Create the bot with any configured parameter;
2. In my bots, select the API Publish Settings option;
3. Click Share;
4. Define any parameter and click create.

The error will appear after a few minutes

## Screenshots

![Captura de tela 2024-06-05 164428](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/9686d11f-c781-47ca-bf38-97ec71b2114f)

**Comment by PolicarpoDi** [comment]
Apparently the error is here according to the cloudwatch log

![Captura de tela 2024-06-05 172138](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/9413e98f-8a24-4db2-bb0e-4772e4ee8058)

**Comment by PolicarpoDi** [comment]
##Error found

Fixed error. I just commented on the section below, where Dbconfig is imported, but in which this function does not exist to be imported.

![Captura de tela 2024-06-05 173501](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/48bc1524-58ef-4694-9256-2ece83a6d6a6)

After that, the api was published.

![print](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/aa5d0ae3-947c-4e8f-8b0e-115e45f7329f)

**Comment by statefb** [comment]
Thank you for reporting. Could you take a trouble to create a PR?

**Comment by PolicarpoDi** [comment]
Of course, I'll create it here.
