### ISSUE TITLE
[Feature Request] Refactoring with Bedrock Converse API

### ISSUE THREAD

**Issue by hustshawn** [aws-samples/bedrock-claude-chat#347]
## Describe the solution you'd like

Amazon Bedrock just released the converse API, which provides a consistant way to invoke models and genereate response. 

## Why the solution needed

Currently the project using Anthropic client for Claude models, and boto3 bedrock client for Mistral models. Both of them are way different in handling invocation and response parsing. It would be ideal to leverage the Converse API to make the code base clean.

## Additional context

Converse API: https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html 

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [ ] Yes
- [ ] No

**Comment by statefb** [comment]
Thank you for your suggestion! While I think it's a good suggestion, I'm concerned that with innovative updates like the multimodal chat in claude3, the Converse API may lag behind in terms of support.

Currently, since there are only two models, Claude and Mistral, for model invocation, we're not having any maintenance issues. Particularly for streaming, we recently [refactored](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/stream.py) it (Also unit test can be found [here](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/tests/test_stream/test_stream.py)), so we don't see much value in migrating. However, if there is a significant need to add models other than Mistral, we may consider adopting the Converse API as you suggested. How do you think?

**Comment by hustshawn** [comment]
It looks a really neat refactoring, and I was not aware of it before. Thank you for mention it.

Yeah, I understand you may not consider to prioritize it at the moment. I can think about potential timeline to go with the Converse API could be either the bedrock invoke API is deprecated, or there is demand to support extra models like Llama3. 

I suppose it's good to keep this ticket open, and see if people have same interest or requirement on extra models support.

**Comment by statefb** [comment]
The converse API is updated: supports document

- Supported file types: "pdf | csv | doc | docx | xls | xlsx | html | txt | md"
- Pass as bytes
- Both Claude / Mistral supports documents, but some of models of Claude / Mistral does not support e.g. Sonnet 3.5

https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/83824aa1-b946-4bf7-9fe2-405ef08bcf36)
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/d78773f1-2a8a-48a9-8f32-363df34eea8f)

**Comment by statefb** [comment]
## Idea notebook
- #198 can be solved by converse API?
  - Upload file on chat text area and parse as byte
  - Send the data through websocket
  - Invoke converse API

**Comment by k70suK3-k06a7ash1** [comment]
@statefb 
こちらのタスクいただきたいです！
アサインいただけると幸いです（他の方で進めれた場合コンフリクトするかなと思いまして念の為）

**Comment by statefb** [comment]
## Refactoring guideline
### General
- No longer need to prepare both [clients](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/bedrock.py#L24-L25)
- No longer need conditional check like [is_anthropic_model](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/usecases/chat.py#L360-L366)
- [compose_args](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/bedrock.py#L33-L50) can be simplified
- [get_bedrock_respose](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/bedrock.py#L258-L313) can be type-safe with Converse API
- [utils.py](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/utils.py#L29-L40) also can be simplified

### Streaming
- Add dedicated handler (called ConverseApiHandler?) on [stream.py](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/stream.py) and remove existing anthropic / bedrock handlers
- No conditional check for [get_streaming_handler_type](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/websocket.py#L271-L275)

### Unit tests
- https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/tests/utils/test_utils.py
- https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/tests/test_stream/test_stream.py
-

**Comment by hustshawn** [comment]
A great milestone. Thank you @statefb
