### ISSUE TITLE
[BUG] Get conversation does not find the conversationId

### ISSUE THREAD

**Issue by PolicarpoDi** [aws-samples/bedrock-claude-chat#349]
## Describe the bug

I published the api, and sent the post according to the documentation, thus generating conversationId and messageId. Then, I tried to test the Get Conversation endpoint, however, when passing the conversationId, it returns 404, as it says that the id I passed was not found.

## To Reproduce

1. According to the api created, I pass the body according to the documentation, and return the conversationId and messageId

![postmessage](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/2091924d-b77c-41a0-ba65-81a202467c70)

2. With the conversationId in hand, I go to the get conversation endpoint

![getconversation](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/c338fdd9-8658-4a21-82a3-f1436715cc53)

but, as it appears on the screen, it gives a 404 error stating that it was not found.

3. I checked the log of this request on coludwatch, but I didn't find anything that could help me solve this error.

![Captura de tela 2024-06-06 170300](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/ecb048d6-fad7-447d-add8-ea090eb9957a)

I saw that the chats are saved in dynamo, but I tried to search for this messageid or conversationId through Athena but I didn't find anything.

I would like to know where this data from the published api is saved (conversationId and messageId) and fix this bug so that I can have the response from the provided endpoints.

Thank you for your help.

**Comment by statefb** [comment]
Thank you for reporting this issue. To investigate, could you check [dynamodb client's response](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/repositories/conversation.py#L160-L163) and the primary keys?

**Comment by PolicarpoDi** [comment]
I checked on Dynamo, and I found the chat bot keys, but the one from the api has no record.

**Comment by PolicarpoDi** [comment]
however, in cloudwatc I found this error below. Would that be permission?

![Captura de tela 2024-06-07 103402](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/8e34007f-60c2-4ece-a71b-5273522b63fd)

**Comment by PolicarpoDi** [comment]
Sorted out. 

It was a permission issue even for the referenced function.

After permission, the API is responding normally.

**Comment by khchan123** [comment]
Also see the same issue, it is fixed after adding the permission manually to `ApiPublishmentStackXXXX-HandlerRoleXXX`.
```
        {
            "Action": [
                "secretsmanager:GetSecretValue"
            ],
            "Resource": [
                "arn:aws:secretsmanager:{REGION}:{ACCOUNT}:secret:VectorStoreClusterSecret{XXX}-{XXXX}"
            ],
            "Effect": "Allow"
        },
```
