### ISSUE TITLE
[Help] Error occurred while responding 

### ISSUE THREAD

**Issue by CTtest725** [aws-samples/bedrock-claude-chat#360]
I am trying to set up bedrock-claude-chat and everything seems fine. After running the required commands in my EC2, there's output of the front end page and I can able to connect to the front end web page and login. However, whenever I tried sending message in the console, it would stuck loading for a while and eventually display the error message " An error occurred while responding." 
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/142006891/a134db67-4a41-40d1-b7d5-e2e194ab4249)
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/142006891/759fa383-1312-41e9-be77-435ec5dd1cb7)

The only reason I could think of is that I do not have access to all the models, which I only have access to Anthropic / Claude 3 Haiku and Cohere / Embed Multilingual. However since I am only using Claude 3 Haiku, I am expecting this to work, but in fact, it didn't. Therefore, I am not sure why this is happening. 

I know this might be a stupid question but I would really appreciate if you could provide some assistance to me. Thank you in advance for helping.

**Comment by PolicarpoDi** [comment]
Friends, I am facing the same problem now. I created a bot and published it on 12/07, and it's working, but I got an error in the model used (I used opus, changed it to sonnet, and it started working again). Today I created another bot, using sonnet, but I'm receiving model error. I have access to all the models, and I'm testing what they could be. If you can find it, share it with us here. 

![Captura de tela 2024-06-12 163301](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/92b22604-ed46-4c70-b631-c25069e3b6a6)

Thanks.

**Comment by PolicarpoDi** [comment]
## Correction

This information I mentioned above is not related to the error that is occurring to me, in fact I discovered that it is a permission issue (every published API generates a role where it must have secretmanager permissions).

![Captura de tela 2024-06-12 213108](https://github.com/aws-samples/bedrock-claude-chat/assets/81364102/0540ef91-1fc7-4afc-a169-126ffde1e177)

**Comment by k70suK3-k06a7ash1** [comment]
@CTtest725 
Do you have model access enabled?
https://github.com/aws-samples/bedrock-claude-chat?tab=readme-ov-file#-super-easy-deployment
