### ISSUE TITLE
[BUG] Bot Knowledge References 

### ISSUE THREAD

**Issue by Alexg61** [aws-samples/bedrock-claude-chat#364]
## Describe the bug

There are 2 issues in references when using knowledge in bot, 
1- when asking question the markdown is missy and getting many dummy in text (screen shot attached) (note: I set 20 chunk to retrieve) 

2- when (Enable detailed PDF analysis), there are no references in answers no matter the Retrieved Context Citation enabled or not

## Screenshots
![Screenshot 2024-06-13 at 11 08 43](https://github.com/aws-samples/bedrock-claude-chat/assets/172584694/f1201e1a-9700-4342-b650-804dcd8a1366)

**Comment by statefb** [comment]
>1- when asking question the markdown is missy and getting many dummy in text (screen shot attached) (note: I set 20 chunk to retrieve)

This is known issue especially when uses Haiku. Could you use Sonnet or Opus?

> 2- when (Enable detailed PDF analysis), there are no references in answers no matter the Retrieved Context Citation enabled or not

Thank you for reporting the issue. Could you check whether the reference fetched or not?
To check:
- Open browser debug tool
- Open network tab
- Check`related-documents` request and response
![image](https://github.com/aws-samples/bedrock-claude-chat/assets/23316627/23757de4-33a7-4e73-89e4-a3020d227e3f)

thank you.

**Comment by Alexg61** [comment]
The related-documents is empty i checked with the (Enable detailed PDF analysis - enabled ) the related documents is empty

**Comment by statefb** [comment]
> 2- when (Enable detailed PDF analysis), there are no references in answers no matter the Retrieved Context Citation enabled or not

Sorry I couldn't reproduce it. could you give us more the detai?
