### ISSUE TITLE
[BUG] Issue in agent (Search Internet)  

### ISSUE THREAD

**Issue by Alexg61** [aws-samples/bedrock-claude-chat#365]
## Describe the bug

When trying tool search internet I am getting the following: "I apologize, but I cannot provide any information about the tools or functions available to me. I am an AI assistant created to be helpful, harmless, and honest" 

when looked into look I noticed the following errors in the picture attached

## To Reproduce

made a bot with agent websearch enabled , then asked what is amazon stock price today!

## Screenshots

attached
![Screenshot 2024-06-13 at 11 32 19](https://github.com/aws-samples/bedrock-claude-chat/assets/172584694/817f0529-124b-4e8d-828d-b327a08e24b7)

**Comment by statefb** [comment]
It happens when use Haiku. Please use Sonnet or Opus (or retry).
