### ISSUE TITLE
[BUG] v 1.1.2 does not show Recently/Starred Bots

### ISSUE THREAD

**Issue by mirecekd** [aws-samples/bedrock-claude-chat#377]
## Describe the bug

After upgrading to v1.1.2 there is no Starred/Recently used Bots anymore

## To Reproduce

1. Use Starred Bot feature

## Screenshots

![ss](https://github.com/aws-samples/bedrock-claude-chat/assets/33002144/a2844c3d-38df-4aa3-aef8-23c39f2ea4c1)

## Additional context

Version v1.1.0 - OK
Did not help logout.
Did not help create new Bot.
I am using OIDC.

**Comment by statefb** [comment]
Could you try the latest version from v1 branch?

**Comment by mirecekd** [comment]
Hi @statefb,

the problem was with older bots - they did not have ConversationQuickStarters section in configuration. I have to dig for logs and the problem was there. 

Log in attachment for your info.

I recreated bots and they are now correctly visible in drawer.

[er-quickstarters.txt](https://github.com/user-attachments/files/15913780/er-quickstarters.txt)

**Comment by statefb** [comment]
Thank you for the investigation! Will fix it
