### ISSUE TITLE
[Feature Request] Add Claude Sonnet 3.5

### ISSUE THREAD

**Issue by jeremylatorre** [aws-samples/bedrock-claude-chat#388]
## Describe the solution you'd like

Add the new model Claude 3.5 sonnet in the chatbot

## Why the solution needed

A clear and concise description of the reason why you want the solution.

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [ ] Yes
- [ ] No

**Comment by statefb** [comment]
please check the latest release.
