### ISSUE TITLE
[BUG] streaming long connected text breaking screen layout 

### ISSUE THREAD

**Issue by Alexg61** [aws-samples/bedrock-claude-chat#390]
## Describe the bug

when printing long connected string, the line is getting out of layout 

## To Reproduce

ask to write long string (200 character) without spaces, check image 

## Additional context

<img width="1040" alt="image" src="https://github.com/aws-samples/bedrock-claude-chat/assets/172584694/186f0e18-17a2-4151-9dd1-6b091e647ae6">

**Comment by k70suK3-k06a7ash1** [comment]
@Alexg61 
This bug has been resolved.
