### ISSUE TITLE
[Feature Request] Enable Stop Generate 

### ISSUE THREAD

**Issue by Alexg61** [aws-samples/bedrock-claude-chat#392]
## Describe the solution you'd like

Sometimes we write the wrong question and we want to stop the generation from start instead of waiting ( sometimes minutes ) 

## Why the solution needed

Saving cost and time and better UX 

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [ ] Yes
- [ ] No

**Comment by statefb** [comment]
duplicated #276

**Comment by statefb** [comment]
@Alexg61 Thank you for creating issues. Before opening, could you check existing issues and pull requests? You don't need to check everything, but it would be helpful if you could check a little bit.
