### ISSUE TITLE
[Feature Request] Add Document to chat ( like Claude in bedrock)

### ISSUE THREAD

**Issue by Alexg61** [aws-samples/bedrock-claude-chat#395]
## Describe the solution you'd like

Bedrock giving the ability to upload document not only image and to make summarize and ask about it.

## Why the solution needed

to prevent copy paste long text, and to enable chat with document or summarize it without the need to copy paste long text 
![Screenshot 2024-06-23 at 16 52 24](https://github.com/aws-samples/bedrock-claude-chat/assets/172584694/76de1ee4-3db2-40e1-9394-c29810d70dc4)

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [ ] Yes
- [ ] No

**Comment by statefb** [comment]
duplicated #198
