### ISSUE TITLE
[Feature Request] Automatic Retries for Throttling by S3 During File Upload

### ISSUE THREAD

**Issue by ViswanathaReddyGajjala** [aws-samples/bedrock-claude-chat#409]
## Describe the solution you'd like

When multiple files are uploaded to create a new bot, it often results in an `Error Message: Request failed with status code 503`. I want to implement automatic retries for these failed uploads. I need to understand if there are any considerations I should take into account before implementing this feature.

## Why the solution needed

For every throttled request, we currently have to manually delete each file. This process can be quite frustrating for our customers. To improve the customer experience, we could implement automatic retries for these failed uploads

## Additional context

I attempted to upload 200+ files and experienced over 140+ throttled uploads. To avoid throttling, I had to upload the files in batches, which was a frustrating process.

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by statefb** [comment]
Ref: https://repost.aws/knowledge-center/http-5xx-errors-s3

**Comment by ViswanathaReddyGajjala** [comment]
Thank you! I noticed that earlier, which is why I'm considering adding support for retries. If you believe this would be beneficial, I can spend some time on this.

**Comment by statefb** [comment]
@ViswanathaReddyGajjala The simplest way would be retrying [uploadFile](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/frontend/src/hooks/useBotApi.ts#L83-L97) n times with a circuit breaker. It'd be appreciated if you could create a PR.

**Comment by ViswanathaReddyGajjala** [comment]
I've tested it with `856` files and S3 didn't throttle the requests. Previously, my account had lower limits which led to the issue. If I encounter this issue in the future, I will raise a Pull Request to address it. For now, I am closing this issue.

**Comment by ViswanathaReddyGajjala** [comment]
I have a follow-up question. For testing purposes, I've uploaded over 800+ files. These are stored in the `_tmp` folder within the main S3 bucket. 

Will these files be automatically deleted after a certain period, or is there a specific process for this? Additionally, would adding appropriate tags to the bucket name be beneficial in this scenario? It would be easy to find the correct bucket.

**Comment by statefb** [comment]
>Will these files be automatically deleted after a certain period, or is there a specific process for this? 

The latter one. These files deleted on the each event. [source](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/usecases/bot.py#L275-L278)

> , would adding appropriate tags

What do you mean "tags" exactly? The [doc](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html) says that we can add tag on the object, but not on the bucket. Another question is, if added, how can we access to the correct bucket easily?

**Comment by statefb** [comment]
Can I reopen this issue? I'm curious why you closed.
