### ISSUE TITLE
[BUG] Deployment failing with Cannot find module '@aws-lambda-powertools/parameters/secrets' error

### ISSUE THREAD

**Issue by catcharbind** [aws-samples/bedrock-claude-chat#418]
## Describe the bug

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

## To Reproduce

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

During automated deployment, the Custom::SetupVectorStore resource fails to deploy.
The lambda function backing this custom resource is failing with the following error.

2024-07-01T17:44:40.322Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@aws-lambda-powertools/parameters/secrets'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@aws-lambda-powertools/parameters/secrets'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}

I have tried to deploy the stack in both us-east-1 and us-west-2 regions. Both times in failed with the same error.

**Comment by statefb** [comment]
Possible cause: https://github.com/aws/aws-cdk/releases/tag/v2.147.3

> lambda-nodejs: breaking change in esbuild causes import module error (https://github.com/aws/aws-cdk/issues/30726) ([06c14b1](https://github.com/aws/aws-cdk/commit/06c14b16d04353e9e108b58edc1450d018c24b12)), closes https://github.com/aws/aws-cdk/issues/30717
