### ISSUE TITLE
ValidationException when trying create a Bot 

### ISSUE THREAD

**Issue by fsipa** [aws-samples/bedrock-claude-chat#471]
Use the Bedrock client to create a new Bot (with excel/csv file upload). The following error happened:

_Knowledge Sync Error
An error occurred while synchronizing Knowledge. Please check the following message:
An error occurred (ValidationException) when calling the InvokeModel operation: Your account is not authorized to invoke this API operation._
![Bildschirmfoto 2024-07-23 um 16 25 21](https://github.com/user-attachments/assets/663a7e18-3fc5-46c3-87eb-351b15922f7d)

Need your help here.

**Comment by statefb** [comment]
Please enables cohere multilingual model on your region ([doc](https://github.com/aws-samples/bedrock-claude-chat?tab=readme-ov-file#-super-easy-deployment)) and try again.

**Comment by fsipa** [comment]
Thank you for your suggestion @statefb  

The enabling of cohere multilingual took much more as expected. 

Now i become following error message after the enabling: 

_An error occurred while synchronizing Knowledge. Please check the following message:
An error occurred (AccessDeniedException) when calling the InvokeModel operation: You don't have access to the model with the specified model ID._


Did i miss something ? After enabling "Cohere multilingual" should i uninstall the "**Bedrock Claude Chat**" and reinstall it again? 
![Bildschirmfoto 2024-07-31 um 20 43 44](https://github.com/user-attachments/assets/a8c17c0e-2f89-44ab-a2f2-edf10a82063c)

Need your help here. Thanks

**Comment by statefb** [comment]
No, you don't need to re-install, re-deploy.  Could you double check if you've enabled the models on the same region as `bedrockRegion` in cdk.json? For more detail for `bedrockRegion`, please also see [here](https://github.com/aws-samples/bedrock-claude-chat#deploy-using-cdk).

**Comment by fsipa** [comment]
Thanks for your reply @statefb 

Ouh la la. I checked it.
We enabled the models in the eu-west-1 region and in cdk.json berockRegion= us-east-1.

So unfortunately, i need to clone the "Bedrock Claude Chat" again, edit the cdk.json file with "bedrockRegion": "eu-west-1" and then deploy again.

Right?

**Comment by Yukinobu-Mine** [comment]
@fsipa Yes, fix cdk.json and then deploy it again.
