### ISSUE TITLE
[BUG] Chat Regenerate does not respect websocket preferences

### ISSUE THREAD

**Issue by ggallo** [aws-samples/bedrock-claude-chat#477]
## Describe the bug

If you deploy with WS streaming disabled, requests to regenerate LLM responses will use WS regardless. This is a hazard for customers that need to deploy without WSS due to APIGW lack of private WS APIs.

## To Reproduce

1. Deploy v1.2.7 with VITE_APP_USE_STREAMING = false
2. Start a conversation and wait for a response
3. Click Regenerate
4. Open devtools and notice the request to regenerate goes over WSS

## Screenshots

Notice the initial POST, then multiple requests to regenerate are opening WSS connections
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/19a2a0d5-84d1-4c58-af10-fcc010139a6b">

**Comment by statefb** [comment]
@ggallo We'll make USE_STREAMING be deprecated because it's hard to maintain the option with keeping backward compatibility to add new features. Thank you for your understanding.
