### ISSUE TITLE
[BUG] Cannot remember context/chat history in Published (Bot) API

### ISSUE THREAD

**Issue by gsukanto** [aws-samples/bedrock-claude-chat#488]
## Describe the bug

branch: `v1`
Bug: Bot cannot remember chat history in the bot published API.
Expectation: Bot can remember chat history like in the UI/FrontEnd that use Websocket for communication.

## To Reproduce

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

1. Create new bot
2. Share and publish the bot
3. Create new conversation/message via `api/conversation` POST API
4. <optional> Get response from `api/conversation/<sender_id>/<message_id>` GET API
5. Ask what is the first message/previous message/all conversation history via `api/conversation` POST API
6. Get response from `api/conversation/<sender_id>/<message_id>` GET API

Expectation: Bot answer with previous message
Actual: Bot said it was its first conversation

## Additional context

Current published API did not accept `parent_id` param.

**Comment by gsukanto** [comment]
Let me know your thought.
What I did in my local setup was create new [trace_to_root](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/app/usecases/chat.py#L211) function to handle `published_api` and use existing function to handle `websocket`. I know its a patch solution.

**Comment by Yukinobu-Mine** [comment]
@gsukanto Thank you for your report. Is it possible to send a pull request or provide your patch solution?

**Comment by gsukanto** [comment]
Hi @Yukinobu-Mine 
I've sent my patching solution: [PR - 490](https://github.com/aws-samples/bedrock-claude-chat/pull/490).
Kindly provide feedback.
Thank you.

**Comment by statefb** [comment]
@gsukanto Hi, thank you for creating PR. To review your PR, I tried to reproduce your problem, but I couldn't that. Could you tell me more detailed reproduction step?

JFYI, I tried following:

- Create a bot with no instruction, no knowledge and publish
- Tried 2 turn conversation
  - First message payload:  
```json
{
  "message": {
    "role": "user",
    "content": [
        {
            "contentType": "text",
            "body": "Tell me famous sight seeing spots."
        }
    ],
    "model": "claude-v3-sonnet"
  }
}
```

  - Second payload:

```json
{
  "conversationId": "xxxxxx",   // issued by first response
  "message": {
    "role": "user",
    "content": [
        {
            "contentType": "text",
            "body": "Your recommendation?"
        }
    ],
    "model": "claude-v3-sonnet"
  }
}
```

**Comment by gsukanto** [comment]
Hi @statefb, 
In my case, I didn't get the same response (recommendation) from the first message.
Attached is the response. I do git pull on `v1` branch at August 16th.
![bedrock-claude-chat-issues-488](https://github.com/user-attachments/assets/73c34d10-3aa2-46e4-b4ee-28c718b64b31)
Thank you.

**Comment by statefb** [comment]
Could you check cloudwatch logs (name is like `/aws/lambda/BedrockChatStack-WebSocketHandlerXXXX`)? It shows whether new conversation created or using existing one. The conversation saved to dynamodb is also logged.

**Comment by CallumCPP** [comment]
@gsukanto I am facing the same issue, how were you able to run the api locally? Also, what is the CLIENT_ID export supposed to be when running the backend locally?
