### ISSUE TITLE
[BUG] Lambda based Youtube video transcript download seems to be blocked

### ISSUE THREAD

**Issue by typex1** [aws-samples/bedrock-claude-chat#491]
## Describe the bug

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

Creating a new Bot including a knowledge base from Youtube transcriptions fails. Error in Frontend: "Failed to detect language: Could not retrieve a transcript for the video https://www.youtube.com/watch?v=Pv0cfsastFs"

This error message is misleading, because what seems to go wrong is not language detection specifically, but the whole transcript API seems to be not usable.

It took me quite some research to have good evidence that AWS owned IP addresses are (currently) blocked from Youtube transcription download. This applies at least to Lambda functions and Cloud9. Tested in us-east-1, eu-central-1 and ap-northeast-1.

## To Reproduce

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

* Create a new Bot, adding any arbitrary Youtube URL as part of the knowledge base. After the sync phase is done, it will show you the related error.

## Additional context

<img width="1024" alt="Screenshot 2024-08-13 at 14 26 53" src="https://github.com/user-attachments/assets/7296d095-493d-41f2-9ca0-c0fd2e6d2cd2">

**Comment by typex1** [comment]
Error situation on the Bot overview list:
<img width="1048" alt="Screenshot 2024-08-13 at 14 47 41" src="https://github.com/user-attachments/assets/5d06745e-9591-46d6-8d27-6caaff58e633">

**Comment by statefb** [comment]
The problem is caused by [youtube-transcript-api](https://github.com/jdepoix/youtube-transcript-api) library. Issues:

- https://github.com/jdepoix/youtube-transcript-api/issues/293
- https://github.com/jdepoix/youtube-transcript-api/issues/303

We may remove the youtube feature in the future for [KnowledgeBase integration](https://github.com/aws-samples/bedrock-claude-chat/issues/440). Thank you for your understanding.
