### ISSUE TITLE
[BUG]Login button doesn't work with Route53 A record pointing to cloudfront distribution

### ISSUE THREAD

**Issue by apheera** [aws-samples/bedrock-claude-chat#493]
## Describe the bug

With actual front end URL everything works but with URL which I registered in route53, it launches the page, and when I click on login button nothing happens.

Cognito is integrated with Azure AD and works well with default frontend URL but not with "route53 simplied record"

- registered cloudfront frontend URL in route53
- ensure there alternate domain name updated in Cloudfront distribution pointing to domain name

## To Reproduce

Browse the DNS via browser example https://friendlyname.com, it brings the login button but when I click on it, nothing happens

## Screenshots

![image](https://github.com/user-attachments/assets/1bc6ae98-cc31-4ef3-a562-d7d74bcdce41)

![image](https://github.com/user-attachments/assets/00d8bb47-91a5-4267-8c27-786758956706)

**Comment by Yukinobu-Mine** [comment]
@apheera How did you register your CloudFront distribution with Route53?
(Manually register in the AWS console, or change the CDK code?)

**Comment by apheera** [comment]
@Yukinobu-Mine 
Yes I created a A record with Alias pointing to cloud front.
Also added Alternate domain name (CNAME) - optional pointing to URL I want to resolve but none is working.
Please note that I have integrated cognito with Azure AD, and authentication and authorisation works fine when it comes to default URL provided by CDK BUT when I register Cloud front to Route53 to a simplified name, that launches but `LOGIN button doesn't work`

and when I inspect the browser I get error below

index-5e8eddf3.js:165 Uncaught (in promise) InvalidOriginException: redirect is coming from a different origin. The oauth flow needs to be initiated from the same origin
    at https://<my_simplified_URL>/assets/index-5e8eddf3.js:165:42368

**Comment by Yukinobu-Mine** [comment]
@apheera Could you please provide the following information?
- Is `Allowed callback URLs` setting of your Cognito user pool set to your custom domain? (in AWS console, Cognito -> User pools -> AuthUserPoolXXXX -> App integration tab -> App client list -> AuthUserPoolClientXXXX -> Hosted UI)
- `identityProviders` setting in your cdk.json. (not including `secretName`)

**Comment by apheera** [comment]
- yes allowed callback is already set to custom domain with the default one which was created by codebase
- Identity provider settings below
    "identityProviders": [
      {
        "service": "oidc",
        "serviceName": "AWS-Bedrock-OpenID",
        "secretName": "bedrock"
      }
    ],

**Comment by Yukinobu-Mine** [comment]
@apheera Thank you. You need to reflect custom domain settings to the front-end environment variables (in [cdk/lib/constructs/frontend.ts](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/cdk/lib/constructs/frontend.ts#L133-L134)) such as:
```
VITE_APP_REDIRECT_SIGNIN_URL: 'https://your-custom-domain',
VITE_APP_REDIRECT_SIGNOUT_URL: 'https://your-custom-domain',
```

**Comment by DTheunis** [comment]
Resolved it - I've added the possibility of customizing this in the cdk.json, could you add it in this project aswell? (I have a lot of customizations that I can't push)
