### ISSUE TITLE
[Feature Request]updating from super easy deployment

### ISSUE THREAD

**Issue by Atlogit** [aws-samples/bedrock-claude-chat#504]
Is there a way to update after using super easy deployment?
Using it, everything works alright, however I can't find a way to update after new versions are released.
Considered using git sync however that requires YAML that doesn't exist with the super-easy deployment.
Any thoughts?

**Comment by CallumCPP** [comment]
Clone the latest version and just run bin.sh again.

**Comment by statefb** [comment]
Thank you @CallumCPP .  
Or just run cdk deploy.

**Comment by axelpina** [comment]
I have some doubts when updating after using "Super-easy deployment":

1) If I run it again in Cloudshell does it redeploy the backend again on a clean slate?

2) If I deployed using optional parameters can I just run `bin.sh` without the parameters I ran or do I need to use them again?

Thank you in advance! 😊

**Comment by axelpina** [comment]
Ran a test with a simple frontend change and just running the `bin.sh` updated the stack in AWS. Please disregard my question above! 😎

**Comment by statefb** [comment]
If you wish to customize more deeply, we recommend to use `cdk deploy`. Let me close this issue.
