### ISSUE TITLE
[BUG] The Provided model dosen't support on-demand throughput

### ISSUE THREAD

**Issue by HeyJiqingCode** [aws-samples/bedrock-claude-chat#508]
## Describe the bug

When Start a conversation with Claude 3 (Opus), there's an error "An error occurred while responding." And the lambda function (WebSocketHandler) logs in CloudWatch show that "Failed to run stream handler: An error occurred (ValidationException) when calling the ConverseStream operation: The provided model doesn't support on-demand throughput."

## Screenshots
![img_v3_02e6_d88daff5-8bfc-48e0-bb0e-6344cd02b0cg](https://github.com/user-attachments/assets/527a8535-8a91-4406-bb7d-53a9925b70c4)
![img_v3_02e6_6abc3d5d-b621-48d4-8b5c-670384884bdg](https://github.com/user-attachments/assets/d8c85f61-a760-4d83-90e5-6e44133c390d)
![img_v3_02e6_1c662972-1b0f-42c3-8905-c4409cd22e7g](https://github.com/user-attachments/assets/e9b7d46f-4e61-431f-b64c-96b37100450d)

**Comment by tomvandenbergh** [comment]
Hi, I have the same problem with Claude 3.5 Sonnet on bedrock in Ireland. DId you manage to find a solution?

**Comment by HeyJiqingCode** [comment]
> Hi, I have the same problem with Claude 3.5 Sonnet on bedrock in Ireland. DId you manage to find a solution?

Hi, I do have tried various methods to fix it, but none worked in Claude 3 Opus. BTW, Claude 3.5 Sonnet works fine in my environment (us-west-2).

**Comment by tomvandenbergh** [comment]
> > Hi, I have the same problem with Claude 3.5 Sonnet on bedrock in Ireland. DId you manage to find a solution?
> 
> Hi, I do have tried various methods to fix it, but none worked in Claude 3 Opus. BTW, Claude 3.5 Sonnet works fine in my environment (us-west-2).

Hi. Ah yes ok. I'm in eu-west-1 where I think 3.5 is fairly newly added. And it has the cross-region inference. I don't know if that could cause any problems?

**Comment by virtualstaticvoid** [comment]
I experienced the same issue when attempting to use Anthropic Claude 3.5 Sonnet in the Paris region.

> The provided model doesn't support on-demand throughput.

It seems that the model can only be used with something called an [inference profile](https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference-use.html) due to [cross-region inference](https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference-use.html)[^1].

![image](https://github.com/user-attachments/assets/c9853b32-27ff-4384-9d80-532f25f29332)

Anyway, it boils down to simply changing the `modelId` used, based on the region in question.

E.g. In my case, the `modelId` was `anthropic.claude-3-5-sonnet-20240620-v1:0` and now it's `eu.anthropic.claude-3-5-sonnet-20240620-v1:0`.

HTH.


[^1]: Never heard of this before today.

**Comment by francoisauclair911** [comment]
@virtualstaticvoid  can I ask where I should update to `eu.anthropic.claude-3-5-sonnet-20240620-v1:0` via the CLI or the `aider.models.yml` or both?

**Comment by virtualstaticvoid** [comment]
> @virtualstaticvoid can I ask where I should update to `eu.anthropic.claude-3-5-sonnet-20240620-v1:0` via the CLI or the `aider.models.yml` or both?

In my case, I changed it in the bedrock.py file.

https://github.com/aws-samples/bedrock-claude-chat/blob/a759f3d91a74d08274d36b9c03117b96b90395f6/backend/app/bedrock.py#L273

Anywhere where the `modelId` is taken as a configuration or parameter...

**Comment by yashk-gloify** [comment]
I'm having the same problem while using Claude in Mumbai region (ap-south-1). Can anyone help?

**Comment by SmartManoj** [comment]
@yashk-gloify  Did you prefix the model ID with the region?

**Comment by yashk-gloify** [comment]
@SmartManoj I did, however, it seems to be an issue with the region. You need to initialize it in Oregon in order for it to work smoothly.

**Comment by virtualstaticvoid** [comment]
You can use the AWS CLI `bedrock list-inference-profiles` command to get the `inferenceProfileId` and `inferenceProfileArn` values:

Provide the relevant region in the `AWS_BEDROCK_REGION` variable. E.g. `us-east-1`.

```bash
aws bedrock list-inference-profiles --region $AWS_BEDROCK_REGION
```

Example of the command output:

```json
{
    "inferenceProfileSummaries": [
        {
            "inferenceProfileName": "US Anthropic Claude 3 Sonnet",
            "description": "Routes requests to Anthropic Claude 3 Sonnet in us-east-1 and us-west-2.",
            "createdAt": "2024-08-26T00:00:00+00:00",
            "updatedAt": "2024-08-26T00:00:00+00:00",
            "inferenceProfileArn": "arn:aws:bedrock:us-east-1:586889964599:inference-profile/us.anthropic.claude-3-sonnet-20240229-v1:0",
            "models": [
                {
                    "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0"
                },
                {
                    "modelArn": "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0"
                }
            ],
            "inferenceProfileId": "us.anthropic.claude-3-sonnet-20240229-v1:0",
            "status": "ACTIVE",
            "type": "SYSTEM_DEFINED"
        },
        ...
    ]
} 
```

**Comment by virtualstaticvoid** [comment]
You can use the AWS CLI `bedrock list-inference-profiles` command to get the `inferenceProfileId` and `inferenceProfileArn` values:

Provide the relevant region in the `AWS_BEDROCK_REGION` variable. E.g. `us-east-1`.

```bash
aws bedrock list-inference-profiles --region $AWS_BEDROCK_REGION
```

Example of the command output:

```json
{
    "inferenceProfileSummaries": [
        {
            "inferenceProfileName": "US Anthropic Claude 3 Sonnet",
            "description": "Routes requests to Anthropic Claude 3 Sonnet in us-east-1 and us-west-2.",
            "createdAt": "2024-08-26T00:00:00+00:00",
            "updatedAt": "2024-08-26T00:00:00+00:00",
            "inferenceProfileArn": "arn:aws:bedrock:us-east-1:xxxxxx:inference-profile/us.anthropic.claude-3-sonnet-20240229-v1:0",
            "models": [
                {
                    "modelArn": "arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0"
                },
                {
                    "modelArn": "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0"
                }
            ],
            "inferenceProfileId": "us.anthropic.claude-3-sonnet-20240229-v1:0",
            "status": "ACTIVE",
            "type": "SYSTEM_DEFINED"
        },
        ...
    ]
} 
```

**Comment by haandol** [comment]
Same bug on meta llama 3.3 70b.

**Comment by spencergoff** [comment]
For anyone using boto3 (in this case I was calling Amazon Nova Micro), this worked for me: 

```
system_list = [
            {
                "text": "Act as a creative writing assistant. When the user provides you with a topic, write a short story about that topic."
            }
]
message_list = [{"role": "user", "content": [{"text": "A camping trip"}]}]
inf_params = {"maxTokens": 500, "topP": 0.9, "topK": 20, "temperature": 0.7}
request_body = {
    "schemaVersion": "messages-v1",
    "messages": message_list,
    "system": system_list,
    "inferenceConfig": inf_params,
}

response = client.invoke_model_with_response_stream(
    modelId='us.amazon.nova-micro-v1:0', body=json.dumps(request_body)
)
```
