### ISSUE TITLE
[Feature Request]In "Deploy using CDK", emphasize that stack "FrontendWafStack" is _always_ in us-east-1

### ISSUE THREAD

**Issue by typex1** [aws-samples/bedrock-claude-chat#511]
## Describe the solution you'd like
It took me a while to find out why I constantly got CDK error messages for "**FrontendWafStack**", and this is the reason:

* I ran "cdk bootstrap" in my target region (eu-central-1)
* I adjusted cdk.json accordingly, as mentioned in the documentation
* But what I did not do is, to also run **"cdk bootstrap" in us-east-1**, because in this case, this is a **multi-region deployment**.
* The resulting error messages for me were misleading, because CDK complains "Deployment failed: Error: FrontendWafStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? "

Maybe for other folks this is obvious, but just wanted to let you know for me it was not.

**Comment by statefb** [comment]
As you mentioned, this sample requires us-east-1 bootstrapped, not only the target region. We'd be appreciated if you could modify the document and create PR. thank you.

**Comment by typex1** [comment]
I am happy to do that. Could you explain why the WAF stack needs to be in us-east-1 at all?

**Comment by statefb** [comment]
>Could you explain why the WAF stack needs to be in us-east-1 at all?

Please refer: https://github.com/aws-samples/bedrock-claude-chat/blob/v1/cdk/bin/bedrock-chat.ts#L56-L58
