### ISSUE TITLE
[BUG] Token validation in middleware

### ISSUE THREAD

**Issue by cyruxOP** [aws-samples/bedrock-claude-chat#516]
Describe the bug
The middleware function while calling get_current_user is not catching any errors returned by get_current_user function.

To Reproduce
Go to bedrock-claude-chat/backend/app/main.py 
Line 94 middleware function . And in the same parent folder dependencies.py when it raises error it is not being handled in the main.py middleware function. Which would lead to errors and multiple invocations.

Ideally when something fails we should return from middleware only without processing further.

**Comment by statefb** [comment]
Please do not ignore the template and provide details. thank you

**Comment by cyruxOP** [comment]
@statefb Added more details
