### ISSUE TITLE
[BUG] Errors when loading files with sonnet 3.5

### ISSUE THREAD

**Issue by CallumCPP** [aws-samples/bedrock-claude-chat#517]
## Describe the bug

When uplaoding files for sonnet 3.5 to process, there is always an error with any file I have tested.
Other models process the file just fine.

## To Reproduce

1. Start a new chat
2. Select sonnet 3.5
3. Upload a file and write a message
4. Error

## Screenshots

Sonnet 3.5
<img width="1456" alt="Screenshot 2024-09-04 at 10 39 21" src="https://github.com/user-attachments/assets/142f715b-39c2-4b9b-a62b-5e21c2944711">

Sonnet 3
<img width="1453" alt="Screenshot 2024-09-04 at 10 39 37" src="https://github.com/user-attachments/assets/4c347f3c-81dd-47ad-aa69-7a18dadd4cd3">

Haiku
<img width="1452" alt="Screenshot 2024-09-04 at 10 39 49" src="https://github.com/user-attachments/assets/fbefaa40-bea9-4ae1-a6a5-3ad14d109691">

## Additional context

I've tested with pdfs and txts.

**Comment by statefb** [comment]
Duplicated: #433
