### ISSUE TITLE
[BUG] Bots with tools enabled don't use instructions

### ISSUE THREAD

**Issue by CallumCPP** [aws-samples/bedrock-claude-chat#519]
## Describe the bug

Bots do not seem to use their instructions when tools are enabled.

## To Reproduce

1. Create a bot with some instructions that will be shown clearly when working
2. Check the instructions work
3. Enable a tool
4. Check again

## Screenshots

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/9c640c8a-58a0-4017-b008-d7fc403c0d49">

# Without tool enabled
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/c77c9593-64c3-4f99-a85b-a5015a41b109">

# With tool enabled
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/e75ed50e-a7f5-4565-964f-6c57c110f552">

**Comment by statefb** [comment]
Thank you for reporting the issue. Currently agent does not support instruction. We're refactoring agent feature on #513 and instruction will be enabled on the future release. Thank you for your understanding.
