### ISSUE TITLE
[BUG] Bot REST API doesn't allow to keep context between responses

### ISSUE THREAD

**Issue by ostap0207** [aws-samples/bedrock-claude-chat#523]
## Describe the bug

When using REST API documented in https://aws-samples.github.io/bedrock-claude-chat/#tag/published_api/operation/health_health_get I couldn't get it to work so that new user messages are not treated as new, but kept as part of the same conversation.

## To Reproduce

1. Start a new conversation using https://aws-samples.github.io/bedrock-claude-chat/#tag/published_api/operation/health_health_get, message text "Please ask me 2 questions, only ask next question after I reply, ignore the result". the response will contain `conversationId`
2. The bot replies with some question, can use https://aws-samples.github.io/bedrock-claude-chat/#tag/published_api/operation/get_conversation_conversation__conversation_id__get to see the conversation
3. Use https://aws-samples.github.io/bedrock-claude-chat/#tag/published_api/operation/post_message_conversation_post with `conversationId` from before

The assumption here is as I reused `conversationId` then bot should ask a second question, but what happens is that it just comments on the answer, which means it doesn't keep the context of the conversation.

**Comment by Yukinobu-Mine** [comment]
When did you publish your API?
The issue of not retaining context between requests was fixed two weeks ago.
The API published after this fix will retain the context.
https://github.com/aws-samples/bedrock-claude-chat/pull/500

**Comment by ostap0207** [comment]
Thanks, I think we are using older version, will close the issue
