### ISSUE TITLE
[Feature Request] Retain erased user chats in backend for compliance

### ISSUE THREAD

**Issue by axelpina** [aws-samples/bedrock-claude-chat#524]
## Describe the solution you'd like

I would like to suggest implementing a feature where chats that users erase from the interface are retained in the backend for compliance purposes. While users may choose to delete or hide their chats, the data would still be stored securely in the backend and remain accessible to administrators for auditing and compliance requirements.

## Why the solution needed

In industries such as finance or legal, strict compliance regulations often require all communications to be stored and auditable. If users have the ability to erase their chats completely, it could violate these compliance standards. Retaining erased chats in the backend will allow companies to remain compliant without altering the user experience on the frontend.

## Additional context

This feature would be helpful for businesses operating under strict compliance regulations such as financial services, healthcare, or any regulated industry where communication retention is mandated. A toggle or flag in the configuration might allow for enabling or disabling this feature based on the organization's needs.

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by statefb** [comment]
The app exports conversation data stored on dynamodb into s3 bucket so that administrators can analyze them ([detail](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/docs/ADMINISTRATOR.md)). Please check if it meets your requirements. thank you

**Comment by axelpina** [comment]
This works, thank you!
