### ISSUE TITLE
[BUG] An error occurred (404) when calling the HeadObject operation: Not Found

### ISSUE THREAD

**Issue by dezhouc2** [aws-samples/bedrock-claude-chat#525]
## Describe the bug

I only changed the content of the prompt and edited the chatbot, then retried some questions, but it occasionally shows new bugs that I haven't seen before. It feels like the chatbot isn't as stable as usual. I’ve posted a screenshot of the bug below. Thank you.

![538b3116-4191-49f5-bb74-2a44e461efd6](https://github.com/user-attachments/assets/83fbeeb4-5ac5-4cd6-9e2f-76fbfd8d994e)

**Comment by statefb** [comment]
Please do not ignore the template and provide details with reproduction steps. thank you

**Comment by dezhouc2** [comment]
> Please do not ignore the template and provide details with reproduction steps. thank you

Thanks for the quick response. it works well in general, however, after some unit tests with the same files uploaded and minor prompt changes, this error pops out which never happened before. I have been using this knowledge database for past 4 months and it seems not stable as usual at least from my personal user experience perspective
