### ISSUE TITLE
[feature request] 続きを出力ボタン (continue button)

### ISSUE THREAD

**Issue by ysekiy** [aws-samples/bedrock-claude-chat#53]
## 概要
「続きを出力」ボタンの実装をしてほしい

## 背景
出力に 30 秒以上かかるリクエストがユーザーから入力された場合、30秒経過後　「回答中にエラーが発生しました。」と出力が消えてしまいます。

## 再現手順
入力はながければなんでもいいのですが、例えば: https://qiita.com/kei31/items/82356c4130b3ab627d32　を入力します。

下記の図のように途中まで出力されます。
<img width="894" alt="Screenshot 2023-10-10 at 19 57 36" src="https://github.com/aws-samples/bedrock-claude-chat/assets/84328663/41f7d6f7-f75d-4031-b5f5-233ac3377099">

29秒後画面出力がクリアされ、「回答中にエラーが発生しました。」と表示されます。
<img width="682" alt="Screenshot 2023-10-10 at 19 54 48" src="https://github.com/aws-samples/bedrock-claude-chat/assets/84328663/30681b56-6253-47a1-b1b7-9cc3a7568151">

<img width="1029" alt="Screenshot 2023-10-10 at 19 55 45" src="https://github.com/aws-samples/bedrock-claude-chat/assets/84328663/8c670233-dd4c-41fe-bc9f-beb68bf5f82d">

根本原因は api-gw と lambda間の統合が max 29秒であることだと考えられます。
https://stackoverflow.com/questions/61617193/aws-api-gateway-websocket-timeout でも同じ議論が見えます。
<img width="1041" alt="Screenshot 2023-10-10 at 19 56 13" src="https://github.com/aws-samples/bedrock-claude-chat/assets/84328663/e15a9795-5186-43ba-a0f3-d0cd8f363922">

## 期待する機能
ユーザー入力+途中まで出力された結果を記録し、再度推論させれば、続きが出力されると思うので、「続きを出力」させる機能がほしい。

`{message: "Endpoint request timed out"` をキャッチした場合は、以下の図のように「続きを出力」をさせるボタンを出してほしい
<img width="218" alt="Screenshot 2023-10-10 at 19 52 10" src="https://github.com/aws-samples/bedrock-claude-chat/assets/84328663/691e6b76-33dc-4f9f-9b83-4fd4147f5f2b">

**Comment by statefb** [comment]
方針: https://github.com/aws-samples/aws-serverless-openai-chatbot-demo/blob/main/v2-websocket/README.md
10/Eまでに修正（目標）

**Comment by statefb** [comment]
下記リリースにて対応しました
https://github.com/aws-samples/bedrock-claude-chat/releases/tag/v0.2.1

30秒以上かかるレスポンスに対応しています。max_tokensで終了する場合はconfig.pyをご調整いただくか、「続けて」などの文言でご対応いただければと存じます。「Continue generating」のボタンはひとまず本Issueでの対応は見送らせていただきました。  

上記対応で難しい場合はまた別途Issue立てていただければと存じますmm

**Comment by ysekiy** [comment]
ありがとうございます！非常に助かります！

**Comment by statefb** [comment]
Implemented on #401
