### ISSUE TITLE
[Feature Request] Cross Region Inference

### ISSUE THREAD

**Issue by statefb** [aws-samples/bedrock-claude-chat#535]
## Describe the solution you'd like

Some region does not support some models.

## Why the solution needed

To enable inference for unsupported regions.

### Implementation guideline
- Only limited regions supports inference profile (currently `us` and `eu` only)
  - we can check if the region supports by `aws bedrock list-inference-profiles --profile <profile-name>`
- Due to the architecture to routing requests, latency happens (see [doc](https://aws.amazon.com/jp/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/)).
  - Add `enableBedrockCrossRegionInference` option to `cdk.json` with the default value false?
- Even the value is set to true, if the `bedrockRegion` is not included in the supported region, model id without cross region inference should be chosen. Also warning log should be added.

Related PR: #531 (reverted)
Related Issues: #508, #527

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [x] Yes
- [ ] No

**Comment by juan-abia** [comment]
If I do cross region inference I get this error:
`Provider eu model does not support chat.`

Any idea how to solve it?

**Comment by axelpina** [comment]
> If I do cross region inference I get this error: `Provider eu model does not support chat.`
> 
> Any idea how to solve it?

There's a PR with a fix in progress but it hasn't been merged: https://github.com/aws-samples/bedrock-claude-chat/pull/536
