### ISSUE TITLE
[BUG] An error occurs during deployment.

### ISSUE THREAD

**Issue by Tsujiba** [aws-samples/bedrock-claude-chat#540]
## Describe the bug
An error occurs during deployment with cdk

## To Reproduce
The following log is recorded, and it appears that the installation of Duckduckgo is failing. As of 9/17, the deployment was completed without any issues.

## Additional context

11 ERROR: process "/bin/sh -c python -m pip install --upgrade pip &&     pip install poetry --no-cache-dir &&     poetry config virtualenvs.create false &&     poetry install --no-interaction --no-ansi --only main &&     poetry cache clear --all pypi" did not complete successfully: exit code: 1
1285 | ------
1286 | > [stage-0 5/6] RUN python -m pip install --upgrade pip &&     pip install poetry --no-cache-dir &&     poetry config virtualenvs.create false &&     poetry install --no-interaction --no-ansi --only main &&     poetry cache clear --all pypi:
1287 | 11.18        75│
1288 | 11.18        76│         # Get the best link
1289 | 11.18        77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
1290 | 11.18        78│
1291 | 11.18
1292 | 11.18 Cannot install duckduckgo-search.
1293 | 11.18
1294 | 11.18   - Installing types-requests (2.32.0.20240712)
1295 | 11.19   - Installing types-retry (0.9.9.4)
1296 | 11.19   - Installing uvicorn (0.23.2)
1297 | ------
1298 | Dockerfile:11
1299 | --------------------
1300 | 10 \|     ENV POETRY_REQUESTS_TIMEOUT=10800
1301 | 11 \| >>> RUN python -m pip install --upgrade pip && \
1302 | 12 \| >>>     pip install poetry --no-cache-dir && \
1303 | 13 \| >>>     poetry config virtualenvs.create false && \
1304 | 14 \| >>>     poetry install --no-interaction --no-ansi --only main && \
1305 | 15 \| >>>     poetry cache clear --all pypi
1306 | 16 \|
1307 | --------------------
1308 | ERROR: failed to solve: process "/bin/sh -c python -m pip install --upgrade pip &&     pip install poetry --no-cache-dir &&     poetry config virtualenvs.create false &&     poetry install --no-interaction --no-ansi --only main &&     poetry cache clear --all pypi" did not complete successfully: exit code: 1

**Comment by LorenzoGabbarini-WS** [comment]
Also having this issue, looks like a problem with that specific version of duckduckgo-search.

> pip install duckduckgo-search==6.2.11
> Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement duckduckgo-search==6.2.11 (from versions: 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.5, 1.0, 1.1, 1.2, 1.3, 1.3.5, 1.4, 1.5, 1.5.1, 1.5.2, 1.6, 1.6.2, 1.7.1, 1.8, 1.8.1, 1.8.2, 2.0.2, 2.1.3, 2.2.0, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.8.1, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 3.0.2, 3.1.1, 3.2.0, 3.3.0, 3.4.1, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.8, 3.9.9, 3.9.10, 3.9.11, 4.0.0, 4.1.0, 4.1.1, 4.2, 4.3, 4.3.1, 4.4, 4.4.1, 4.4.2, 4.4.3, 4.5.0, 5.0b0, 5.0b1, 5.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0b1, 5.3.0b2, 5.3.0b3, 5.3.0b4, 5.3.0, 5.3.1b1, 5.3.1, 6.0.0, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5, 6.1.6, 6.1.7, 6.1.8, 6.1.9, 6.1.11, 6.1.12, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.2.5, 6.2.6, 6.2.7, 6.2.8b1, 6.2.8, 6.2.9, 6.2.10, 6.2.11b1, 6.2.12)
ERROR: No matching distribution found for duckduckgo-search==6.2.11


I temporarely worked around the error by adding commands to the CodeBuild Project's Buildspec to get version 6.2.12 (note that this also requires updating hashes).

**Comment by Tsujiba** [comment]
I try ''pip install duckduckgo-search==6.2.11''
result is "Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement duckduckgo-search==6.2.11 (from versions: 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.5, 1.0, 1.1, 1.2, 1.3, 1.3.5, 1.4, 1.5, 1.5.1, 1.5.2, 1.6, 1.6.2, 1.7.1, 1.8, 1.8.1, 1.8.2, 2.0.2, 2.1.3, 2.2.0, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.8.1, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 3.0.2, 3.1.1, 3.2.0, 3.3.0, 3.4.1, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.8, 3.9.9, 3.9.10, 3.9.11, 4.0.0, 4.1.0, 4.1.1, 4.2, 4.3, 4.3.1, 4.4, 4.4.1, 4.4.2, 4.4.3, 4.5.0, 5.0b0, 5.0b1, 5.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0b1, 5.3.0b2, 5.3.0b3, 5.3.0b4, 5.3.0, 5.3.1b1, 5.3.1, 6.0.0, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5, 6.1.6, 6.1.7, 6.1.8, 6.1.9, 6.1.11, 6.1.12, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.2.5, 6.2.6, 6.2.7, 6.2.8b1, 6.2.8, 6.2.9, 6.2.10, 6.2.11b1, 6.2.12)
ERROR: No matching distribution found for duckduckgo-search==6.2.11"

it is need for change version 6.2.11 to 6.2.12？

**Comment by statefb** [comment]
According to the [release](https://github.com/deedy5/duckduckgo_search/releases), 6.2.11 is no longer available. We might want to update the [lockfile](https://github.com/aws-samples/bedrock-claude-chat/blob/v1/backend/poetry.lock) to reflect the updates of duck-duck go (PR would be appreciated).
