### ISSUE TITLE
[BUG] Template validation failed

### ISSUE THREAD

**Issue by spaiusecase** [aws-samples/bedrock-claude-chat#550]
I am having trouble with deploying.

When I run this command: ./bin.sh. I get the below error. Could someone assist? What am I doing wrong?

Are you a new user starting with v1.x or later? (y/N): y
Starting deployment...
Template validation failed

**Comment by axelpina** [comment]
Please follow the bug reporting template.

**Comment by cusackeoin** [comment]
I had this issue when the role I was using didn't have access to CloudFormation to complete the command 
`aws cloudformation validate-template --template-body file://deploy.yml  > /dev/null 2>&1`
