### ISSUE TITLE
[BUG] [ThrottlingException] An error occurred while responding for Claude Sonnet 3.5

### ISSUE THREAD

**Issue by AdityaIndoori** [aws-samples/bedrock-claude-chat#553]
## Describe the bug

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  
Any messages I send to Claude Sonnet 3.5 get throttled and subsequently show the error in UI: "An error occurred while responding.". I see an error in Cloudwatch logs for the `/aws/lambda/BedrockChatStack-WebSocketHandler` logstream: 

```
Failed to run stream handler: An error occurred (ThrottlingException) when calling the ConverseStream operation (reached max retries: 4): Too many requests, please wait before trying again.
```

## To Reproduce

**Filling out this field will help us investigate the issue efficiently. Providing detailed information allows us to set the appropriate priority. We appreciate your cooperation.**  

1. Go to new chat
2. Select Claude 3.5 Sonnet
3. Send a message
4. Expect a reply
5. Send another message within 5 seconds after the reply
6. See error: "An error occurred while responding."

## Screenshots
![image](https://github.com/user-attachments/assets/8ae899a8-907e-40b4-8ec4-285411a7ea9e)

## Additional context

* AWS Region: us-east-1
* Did NOT purchase any provisioned throughput

**Comment by statefb** [comment]
Does it always happen? If not so, this issue is not related to this repository.

**Comment by AdityaIndoori** [comment]
Yes, it is a persistent issue that I am able to reproduce every time

**Comment by statefb** [comment]
Does it still occur when you use management console?

**Comment by AdityaIndoori** [comment]
Yup it does. Looks like Claude 3.5 Sonnet has provisioned throughput only in us-west-2, where as I deployed everything in us-east-1. Is there a way to use the us-west-2 sonnet 3.5 while everything is as-is in us-east-1?

**Comment by statefb** [comment]
See: [bedrockRegion option](https://github.com/aws-samples/bedrock-claude-chat?tab=readme-ov-file#deploy-using-cdk)

**Comment by AdityaIndoori** [comment]
Using us-west-2 solved it. Thank you!
