### ISSUE TITLE
[BUG] Impossible to select a custom bot on mobile device

### ISSUE THREAD

**Issue by jeremylatorre** [aws-samples/bedrock-claude-chat#555]
## Describe the bug

When I want to use the app on a mobile device, I cannot select a custom bot in the bot console. This is not possible to scroll laterally, I can only access to the "Edit" button

## To Reproduce

Resize the window or simulate a mobile device > go to bot console.

## Screenshots

![Capture d’écran 2024-10-03 à 10 27 18](https://github.com/user-attachments/assets/cafcb5b2-619d-4344-8ab6-1ffeabda12a5)

**Comment by ClementVanPeuter** [comment]
+1
