### ISSUE TITLE
[Feature Request] Add hierarchical / semantic chunking strategy

### ISSUE THREAD

**Issue by statefb** [aws-samples/bedrock-claude-chat#558]
## Describe the solution you'd like

Add hierarchical / semantic chunking strategy. For more detail, visit [doc](https://docs.aws.amazon.com/bedrock/latest/userguide/kb-chunking-parsing.html).

## Why the solution needed

Both of advanced chunking strategies has been proved that they improve RAG accuracy.

## Additional context

Sample code for `generative-ai-cdk-constructs` can be found [here](https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/cdk-lib/bedrock#knowledge-base---chunking-strategies)

## Implementation feasibility

Are you willing to discuss the solution with us, decide on the approach, and assist with the implementation?

- [ ] Yes
- [ ] No

**Comment by Tsujiba** [comment]
@statefb 
Would it be ok if I try submitting a pull request for this issue?

**Comment by statefb** [comment]
@Tsujiba Of course! I assigned you to this issue. From the next time, please feel free to assign yourself to issues when proceed to work on it!
