### ISSUE TITLE
bin/bedrock-chat.js instead of bin/cdk.js ?

### ISSUE THREAD

**Issue by antoinefradin** [aws-samples/bedrock-claude-chat#559]
https://github.com/aws-samples/bedrock-claude-chat/blob/dd51a2ec5e332c6c3a1adf64913ea1d547d83e1e/cdk/package.json#L5

Hello, 

I have a question about the package.json file. Can someone explain me why there is `bin/cdk.js`? 
```
"bin": {
    "cdk": "bin/cdk.js"
  },
```

I don't see any cdk.js file in the tree directory. Thanks!

**Comment by statefb** [comment]
The statement would have been proposed in a very early version of CDK. This is not related to this repository, so close this issue.
