### ISSUE TITLE
I18n for more than the login dialog

### ISSUE THREAD

**Issue by wzr1337** [aws-samples/bedrock-claude-chat#57]
Happy to help translation to english and german once the i18n framework is decided.

**Comment by statefb** [comment]
Thank you so much for your cooperation! We are going to introduce i18n (en / ja) using framework by the end of Oct.

**Comment by statefb** [comment]
@wzr1337 We introduced i18n framework [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector). Configuration are available on here: https://github.com/aws-samples/bedrock-claude-chat/tree/main/frontend/src/i18n

We'd be appreciate and happy if you could help to translate 🙇

**Comment by statefb** [comment]
#172
