### ISSUE TITLE
[Feature Request] Custom lambda function retrieval

### ISSUE THREAD

**Issue by PeterRayner** [aws-samples/bedrock-claude-chat#576]
## Describe the solution you'd like

in the bots, i would like to be able to choose an existing lambda function to query Amazon Athena, to query data sources, so i can ask Claude about my data, and I can configure the lambda/bot with the right credentials to return data from RDS or S3 and tell me about it.

## Why the solution needed

This is a great addition to any datalake and allows non technical users to get easy information from their datalakes while not having to code. The same could be said with Redshift, but Athena alone for now would be amazing.

## Additional context

[Add any other context or screenshots about the feature request here.]

(https://repost.aws/articles/ARDEyn8B0aQLud6ZGK7yyX3Q/generative-ai-with-amazon-bedrock-and-amazon-athena)

## Implementation feasibility

Are you willing to collaborate with us to discuss the solution, decide on the approach, and assist with the implementation?

- [ ] Yes, I am able to implement the feature and create a pull request.
- [ X] No, I am unable to implement the feature, but I am open to discussing the solution.

**Comment by statefb** [comment]
Please consider using [agent](https://github.com/aws-samples/bedrock-claude-chat/blob/v2/docs/AGENT.md#how-to-develop-your-own-tools). For SQL generation, also consider to use [v1.3.0](https://github.com/aws-samples/bedrock-claude-chat/releases/tag/v1.3.0) (refer `examples` directory).
