### ISSUE TITLE
[BUG] No conversations found

### ISSUE THREAD

**Issue by zeickan** [aws-samples/bedrock-claude-chat#579]
Hi,

I'm having issues using the published API from my Bedrock.

I following the instructions described in: https://aws-samples.github.io/bedrock-claude-chat/ to create my request in Postman

For more context, I'm using v2 installed using 🚀 Super-easy Deployment, my specific problem is:

I can connect without any issues, the Health Check API responds Ok

<img width="566" alt="Captura de pantalla 2024-10-30 a la(s) 8 15 53 p m" src="https://github.com/user-attachments/assets/333f3e65-974d-4903-94c5-920afeec31d4">

Creating a conversation works correctly (I get the expected response according to the documentation)

<img width="740" alt="Captura de pantalla 2024-10-30 a la(s) 8 16 04 p m" src="https://github.com/user-attachments/assets/75c2aeb2-3edf-4bb0-99bb-85db5c0df6c8">

Querying the conversation always results in a not found error.

<img width="835" alt="Captura de pantalla 2024-10-30 a la(s) 8 16 18 p m" src="https://github.com/user-attachments/assets/7523d47a-ed2c-4e2c-bf0d-99707451ebb1">

I require add additional permissions like groups in Cognito or something? 

Tnx

**Comment by statefb** [comment]
Please follow the template instruction. thx

**Comment by caosinf777** [comment]
same problem here using the template.
