### ISSUE TITLE
[BUG]Bedrock Claude Chatで最初の質問から、「回答中にエラーが発生しました。」で先に進めません。

### ISSUE THREAD

**Issue by todalaba** [aws-samples/bedrock-claude-chat#625]
## Describe the bug
I am new to Amazon cloud. Never used before for the on-going project. Just a test project I have done before.
I wanted to try Bedrock Claude Chat.
When I input
"Which city is the capital of Japan?

## To Reproduce

1.git clone https://github.com/aws-samples/bedrock-claude-chat.git
2.cd bedrock-claude-chat
   chmod +x bin.sh
   ./bin.sh
3. Go to 'https://xxxxxxxx.cloudfront.net/.'
4. Login
5. Input  "Which city is the capital of Japan?
6. See error as Screenshot

## Screenshots

![SnapCrab_NoName_2024-12-5_10-16-28_No-00](https://github.com/user-attachments/assets/f7cc95d7-0b1f-4867-8193-310f16aed894)

**Comment by statefb** [comment]
Have you enabled LLM models?
> In the us-east-1 region, open [Bedrock Model access](https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/modelaccess) > Manage model access > Check all of Anthropic / Claude 3, all of Amazon / Nova, Amazon / Titan Text Embeddings V2 and Cohere / Embed Multilingual then Save changes.

**Comment by todalaba** [comment]
Thank you very much for your information. It is working now.
