### ISSUE TITLE
[BUG]Nova doesn't work

### ISSUE THREAD

**Issue by HirokiNakatani** [aws-samples/bedrock-claude-chat#629]
## Describe the bug
If you select Nova to chat with an existing RAG bot, an error will occur.

![{69CDFA60-07B8-4F66-B959-37ACD833C9F5}](https://github.com/user-attachments/assets/74ecf34f-bda5-4598-916c-9e78f79db0c0)
![{DDEEDBC7-B908-4FF7-A361-F40B9A60594D}](https://github.com/user-attachments/assets/7cf784c7-e501-4c42-8b83-092274756f4c)

**Comment by axelpina** [comment]
This seems to be also happening with the other models aswell.

**Comment by HirokiNakatani** [comment]
In other models, it occurs after several exchanges, but in nova, it occurs from the beginning to the end.

**Comment by HirokiNakatani** [comment]
This occurs on all nova series.

**Comment by statefb** [comment]
Please provide cloudwatch logs for websocket handler.

**Comment by axelpina** [comment]
> Please provide cloudwatch logs for websocket handler.

Please let me know if this is sufficient information

![image](https://github.com/user-attachments/assets/0930a668-7508-4e50-b247-36ec12ab4ed5)

I believe the Bedrock API is reporting that a `guardContent` field is empty for one of the `ContentBlock` objects. When handling a user message and applying guardrails with `grounding_source`, the code returns a list with `{"guardContent": grounding_source}` as the first item. If the `grounding_source` is missing or does not contain the required text fields, Bedrock rejects the request.

```python

if (
    role == "user"
    and guardrail
    and guardrail.grounding_threshold > 0
    and grounding_source
):
    return [
        {"guardContent": grounding_source},
        {
            "guardContent": {
                "text": {"text": c.body, "qualifiers": ["query"]}
            }
        },
    ]
```

If `grounding_source` is empty or does not contain a text field, the first element in this returned list will have empty guard content.

EDIT: My Cloudwatch logs show a completely different issue vs. the one from the OP. I've made a new ticket to keep things better organized: https://github.com/aws-samples/bedrock-claude-chat/issues/637

**Comment by HirokiNakatani** [comment]
Provides cloudwatch logs for websocket handlers.

![{75B4D4F4-2855-4246-9739-C065B6E9190F}](https://github.com/user-attachments/assets/69c7b148-9843-4f3a-9345-c93fefb6c3cc)

**Comment by lopez-hector** [comment]
We're currently inspecting this. It seems to be happening when the tool config input scheme has the "title" key.

Please let me know if you can fix the error by deleting this key when Nova is selected. 

We're working on testing more thoroughly now. We've had success by deleting the `title` key in the toolConfig.

```
'toolConfig': {
    'tools': [
        {
            'toolSpec': {
                'name': 'internet_search',
                'description': 'Search the internet for information.',
                'inputSchema': {
                    'json': {
                        'properties': {
                            'query': {
                                'description': 'The query to search for on the internet.',
                                'title': 'Query',
                                'type': 'string'
                            },
                            'country': {
                                'description': 'The country code you wish for search. Must be one of: jp-jp (Japan), kr-kr (Korea), cn-zh (China), fr-fr (France), de-de (Germany), es-es (Spain), it-it (Italy), us-en (United States)',
                                'title': 'Country',
                                'type': 'string'
                            },
                            'time_limit': {
                                'description': "The time limit for the search. Options are 'd' (day), 'w' (week), 'm' (month), 'y' (year).",
                                 'title': 'Time Limit',
                                 'type': 'string'
                            }
                        },
                       'required': ['query', 'country', 'time_limit'],
                       'title': 'InternetSearchInput', # This KEY
                       'type': 'object'
                   }
               }
           }
       }
   ]
}
```

**Comment by statefb** [comment]
@lopez-hector Thank you for your detailed investigation. As you mentioned, [official doc](https://docs.aws.amazon.com/ja_jp/bedrock/latest/userguide/tool-use-inference-call.html) says that no need to add `title` to the request. We'll fix this bug (cannot tell the ETA) but it'd be nice if you could create a PR. Thank you for your understanding.

**Comment by axelpina** [comment]
> We're currently inspecting this. It seems to be happening when the tool config input scheme has the "title" key.
> 
> Please let me know if you can fix the error by deleting this key when Nova is selected.
> 
> We're working on testing more thoroughly now. We've had success by deleting the `title` key in the toolConfig.
> 
> ```
> 'toolConfig': {
>     'tools': [
>         {
>             'toolSpec': {
>                 'name': 'internet_search',
>                 'description': 'Search the internet for information.',
>                 'inputSchema': {
>                     'json': {
>                         'properties': {
>                             'query': {
>                                 'description': 'The query to search for on the internet.',
>                                 'title': 'Query',
>                                 'type': 'string'
>                             },
>                             'country': {
>                                 'description': 'The country code you wish for search. Must be one of: jp-jp (Japan), kr-kr (Korea), cn-zh (China), fr-fr (France), de-de (Germany), es-es (Spain), it-it (Italy), us-en (United States)',
>                                 'title': 'Country',
>                                 'type': 'string'
>                             },
>                             'time_limit': {
>                                 'description': "The time limit for the search. Options are 'd' (day), 'w' (week), 'm' (month), 'y' (year).",
>                                  'title': 'Time Limit',
>                                  'type': 'string'
>                             }
>                         },
>                        'required': ['query', 'country', 'time_limit'],
>                        'title': 'InternetSearchInput', # This KEY
>                        'type': 'object'
>                    }
>                }
>            }
>        }
>    ]
> }
> ```

As far as I am aware the issue seems to stem from the `_generate_input_schema` method _(in `agent_tool.py`)_ . If possible, could you explain how you're removing the `title` key from the JSON?
