### ISSUE TITLE
Cannot deploy to another region due to WAF V2 is only available in us-east-1

### ISSUE THREAD

**Issue by fbukevin** [aws-samples/bedrock-claude-chat#633]
Hi we currently encounter an issue to deploy the chat agent to ap-northeast-1. And we continuously encountered the error:

```
FrontendWafStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
```

We finally resolved it with by setting WAF to region "us-west-1" according to this [post](https://stackoverflow.com/a/75872197/2306349). But there is no any document in this repository mentioned about that. I noticed that in file 
https://github.com/aws-samples/bedrock-claude-chat/blob/eca2c666c748d10efbb08d71fde583184d887643/cdk/bin/bedrock-chat.ts#L49
mentioned it and it's almost 1 year ago 😂

Is there any progress of the deployment of WAF V2 to other region?

Or other workarounds are also welcome!

Thank you !

**Comment by statefb** [comment]
We must to deploy WAF for cloudfront on us-east-1 ([doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webacl.html)). Have you run `cdk bootstrap --region us-east-1` before deployment?

**Comment by fbukevin** [comment]
Hi statefb, thanks for your document. I didn't checked in AWS official document but only this repo.
As a result, I simply ran `cdk bootstrap aws://<ACCOUNT_ID>/ap-northeast-1`. I changed `us-east-1` to `ap-northeast-1` is becuase I didn't know I should not change that. Now I understand. 

I just wonder the availability of WAFv2 in other regions.

**Comment by statefb** [comment]
> I just wonder the availability of WAFv2 in other regions.

From document:
> For CLOUDFRONT, you must create your WAFv2 resources in the US East (N. Virginia) Region, us-east-1.

Check it out!

**Comment by statefb** [comment]
If works, please close, thanks

**Comment by fbukevin** [comment]
I would like to know if there is a plan to deploy WAFv2 to other regions. Or add this information in README should be helpful for other users(either the official document or the Caution explicitly).

Thank you.
