### ISSUE TITLE
[BUG] Bot creation process hangs indefinitely during PDF synchronization with excessive OpenSearch costs

### ISSUE THREAD

**Issue by fjlana** [aws-samples/bedrock-claude-chat#641]
Description:
When attempting to create a new bot using PDF files (10-12 pages), the synchronization process becomes stuck in an infinite loop. This results in extended processing times (20+ hours) and generates significant unexpected OpenSearch costs without completing the bot creation.

Steps to reproduce:
Access Bot console
Initiate new bot creation
Upload PDF file (10-12 pages)
Start synchronization process
Observe that the process remains in "synchronizing" state indefinitely

Expected behavior:
PDF synchronization should complete within a reasonable timeframe (minutes, not hours)
OpenSearch costs should be proportional to the document size
Clear indication of synchronization progress or failure
Timeout in case it takes more than X hours

Current behavior:
Synchronization process never completes
System remains in "synchronizing" state for 20+ hours
Generates excessive OpenSearch costs
No error messages or timeout notifications
No indication of process status or progress

Environment:
Bedrock claude version: 2.3.0
PDF file size: 10-12 pages
Browser: Chrome

Thank you

**Comment by statefb** [comment]
Cloud you check StepFunctions log for embedding process?

**Comment by fjlana** [comment]
Hello, 

After checking I see this error,. I have requested access to titan-embed
{
  "cause": {
    "errorType": "ValidationException",
    "errorMessage": "Knowledge base role arn:aws:iam::686255976286:role/AmazonBedrockExecutionRoleForKnowledgeBaseBrChatK9METHKBC954B651 is not able to call specified bedrock embedding model arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0: You don't have access to the model with the specified model ID. (Service: BedrockRuntime, Status Code: 403, Request ID: bc5da69b-9397-4af7-a302-d9e7b2dd30cd)",
    "trace": [
      "ValidationException: Knowledge base role arn:aws:iam::686255976286:role/AmazonBedrockExecutionRoleForKnowledgeBaseBrChatK9METHKBC954B651 is not able to call specified bedrock embedding model arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0: You don't have access to the model with the specified model ID. (Service: BedrockRuntime, Status Code: 403, Request ID: bc5da69b-9397-4af7-a302-d9e7b2dd30cd)",
      "    at de_ValidationExceptionRes (/var/runtime/node_modules/@aws-sdk/client-bedrock-agent/dist-cjs/index.js:3164:21)",
      "    at de_CommandError (/var/runtime/node_modules/@aws-sdk/client-bedrock-agent/dist-cjs/index.js:3067:19)",
      "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20",
      "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/core/dist-cjs/index.js:165:18",
      "    at async /var/runtime/node_modules/@aws-sdk/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38",
      "    at async /var/runtime/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22",
      "    at async Runtime.w [as handler] (/var/task/index.js:1:1218)"
    ]
  },
  "error": "ValidationException"
}

![stepfunctions_graph](https://github.com/user-attachments/assets/09a72033-5c43-40fd-9afa-fc540f8fbe70)

Thank you

**Comment by statefb** [comment]
Have you enabled the models?
> In the us-east-1 region, open [Bedrock Model access](https://us-east-1.console.aws.amazon.com/bedrock/home?region=us-east-1#/modelaccess) > Manage model access > Check all of Anthropic / Claude 3, all of Amazon / Nova, Amazon / Titan Text Embeddings V2 and Cohere / Embed Multilingual then Save changes.

**Comment by fjlana** [comment]
thank you, all working :)
