### ISSUE TITLE
[BUG]Error when clicking on references.

### ISSUE THREAD

**Issue by ghost** [aws-samples/bedrock-claude-chat#646]
## Describe the bug

Clicking on e.g. [1] will show partial references, but clicking on the actual file stored in s3 will result in an error.
Version 2.21

## To Reproduce

1. click on the reference, e.g. [1].
2. click on the actual file at the bottom
3. originally, we would like the references stored in s3 to be displayed here, but an error occurs.

## Screenshots
![issue2](https://github.com/user-attachments/assets/80c1a3bd-1719-42ac-8df3-104f710ca433)

## Additional context
It worked fine in Version 1.30.

**Comment by ghost** [comment]
It looks like a simple bug, because there is a ‘//’ in the access URL.

**Comment by Yukinobu-Mine** [comment]
@kouno7 Fixed in main branch. Thank you for your report!
