### ISSUE TITLE
[Feature Request]I want to create a bot that does not use RAG

### ISSUE THREAD

**Issue by HirokiNakatani** [aws-samples/bedrock-claude-chat#648]
## Describe the solution you'd like
I want to give instructions to LLM and create a chat that does not use the RAG function

## Why the solution needed
There are use cases that do not utilize RAG.

## Additional context
If you can create chats other than RAG as shown below, the range of usage will expand.
https://github.com/aws-samples/generative-ai-use-cases-jp

## Implementation feasibility

Are you willing to collaborate with us to discuss the solution, decide on the approach, and assist with the implementation?

- [x] Yes, I am able to implement the feature and create a pull request.
- [ ] No, I am unable to implement the feature, but I am open to discussing the solution.

**Comment by statefb** [comment]
You can create a bot without RAG by setting "Knowledge" section as empty.

**Comment by HirokiNakatani** [comment]
It's done. thank you.
