### ISSUE TITLE
[BUG] Bots with Spanish knowledge bases using Amazon Nova model break words with accents

### ISSUE THREAD

**Issue by axelpina** [aws-samples/bedrock-claude-chat#656]
## Describe the bug

When using a bot that has instructions and knowledge base in Spanish with Amazon Nova, replies from the models break when the words have accents.

## To Reproduce

1. Go to a bot that has instructions and knowledge base in spanish
2. Ask it anything related to the knowledge base
3. Watch as the text breaks

## Screenshots

Amazon Nova
![image](https://github.com/user-attachments/assets/9f49146d-6b93-4748-abff-c9ca647973c8)

Sonnet 3.5 v2 - _With Sonnet 3.5 v2, the text doesn't break_

![image](https://github.com/user-attachments/assets/ad56d404-9dd7-4f6f-a219-0a4ed9fbcf2a)

## Additional context

N/A

**Comment by statefb** [comment]
Is this the issue related this sample? Seems aws-bedrock related problem. if so, close this because it is out of the scope of our asset. thank you
