### ISSUE TITLE
Please tell me how to assign the same tag to all resources.

### ISSUE THREAD

**Issue by HirokiNakatani** [aws-samples/bedrock-claude-chat#658]
I would like to assign the same cost allocation tag to all resources as much as possible. How do I set it up?

I would like to add a cost allocation tag.

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the BedrockChatStack to include a cost allocation tag property and apply it to resources where possible.

You can review changes in this commit: https://github.com/wwqwq2313/aws-samples-bedrock-claude-chat-658/commit/a0e649ad1067a0ef661d2ef939ceb7ac490e8319.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by HirokiNakatani** [comment]
thank you.
i will try.

It would be convenient if it was made an optional feature at the time of installation.

**Comment by HirokiNakatani** [comment]
It seems possible to tag each CDK at once as shown below.
https://dev.classmethod.jp/articles/aws_cdk_add_common_tag/

**Comment by HirokiNakatani** [comment]
I was able to solve it.
I would like to request additional functionality.
