### ISSUE TITLE
API call and Streaming chunks

### ISSUE THREAD

**Issue by webbhlin** [aws-samples/bedrock-claude-chat#69]
Thanks for sharing this awesome project to give us more ideas to develop AWS Bedrock!

I would like to know how to modify the frontend code to call api (invoke()) instead of streaming via web socket (invoke_model_with_response_stream()). 

Please give me some guidance to use your code more properly. 

Best Regards,
Webber

**Comment by statefb** [comment]
We can use non-streaming api by:

- Set `VITE_APP_USE_STREAMING` as false
  -  Ref: https://github.com/aws-samples/bedrock-claude-chat#using-streaming
- Use POST /conversation
  - Ref: https://github.com/aws-samples/bedrock-claude-chat/blob/main/backend/app/route.py#L32

Some comments on the code are written in Japanse, but we'll translate to english later. Sorry for inconvenience.
