### ISSUE TITLE
Error on switching languages

### ISSUE THREAD

**Issue by tmokmss** [aws-samples/bedrock-claude-chat#76]
When the browser default language is configured to languages other than `en,ja,ko,zh`, the frontend throws an error when trying to switching languages.

## Reproduction

Set the browser default language to en-us (or whatever unsupported languages):

<img width="729" alt="image" src="https://github.com/aws-samples/bedrock-claude-chat/assets/7490655/5263efb2-7be7-4f09-896d-d2df66e486c4">

Clear local storage for the page to reset `i18nextLng`, then open the page, login, and try to switch language.

The error I get:

```
Unexpected Application Error!
props.options.filter(...)[0] is undefined

Select/selectedLabel<@http://localhost:5173/src/components/Select.tsx?t=1698727269604:25:52
mountMemo@http://localhost:5173/node_modules/.vite/deps/chunk-GYWC62UC.js?v=f26ec844:12817:27
useMemo@http://localhost:5173/node_modules/.vite/deps/chunk-GYWC62UC.js?v=f26ec844:13141:24
useMemo@http://localhost:5173/node_modules/.vite/deps/chunk-HS5T2ZWL.js?v=f26ec844:1094:29
Select@http://localhost:5173/src/components/Select.tsx?t=1698727269604:24:32
...
```

## Possible solution
Something like this will fix the issue (check if the find result is undefined):

https://github.com/aws-samples/bedrock-claude-chat/blob/c1cdcbfefd4f93ce6ad0ba453a2eb48370fa8669/frontend/src/components/Select.tsx#L18-L22

```diff
-    return props.value === ''
-      ? ''
-      : props.options.filter((o) => o.value === props.value)[0].label;
+    return props.options.find((o) => o.value === props.value)?.label ?? '';
```

**Comment by statefb** [comment]
Thank you so much for reporting error handling issue with the detail. We'd be happy if you could create a PR 🙇
