### ISSUE TITLE
Is the SNS necessary in your design?

### ISSUE THREAD

**Issue by tomaszdudek7** [aws-samples/bedrock-claude-chat#89]
Hi there. I'm just wondering if the SNS as the "decoupling" mechanism is necessary and/or if there was a specific requirement or reasoning behind it.

Your flow of getting a response from a model is as follows:
1. front-end connects to a websocket  - which, under the hood, invokes the _publisher Lambda_ - but it doesn't do much due to `route_key` being equal to `$connect`
2. then, front-end sends the user prompt to the open websocket (https://github.com/aws-samples/bedrock-claude-chat/blob/c2eec81489497e6ccabcd4d6009e64053b44a12d/frontend/src/hooks/usePostMessageStreaming.ts#L25) - it also triggers the same _publisher Lambda_. However, this time, it actually pushes the prompt forward to the SNS because the `route_key` is different.
3. now, the SNS invokes the _websocket Lambda_, which streams the response back to the websocket (https://github.com/aws-samples/bedrock-claude-chat/blob/main/backend/app/websocket.py#L77)

However, if (instead of being SNS consumer) your _websocket Lambda_ was just a different route on the WS API gateway (lets call it `/invoke`), then the flow could look as follows:
1. front-end connects to a websocket  - which, under the hood, invokes the _publisher Lambda_ - but it doesn't do much due to `route_key` being equal to `$connect`
2. front-end sends the user prompt to the open websocket **as an action `/invoke`** - it triggers the _websocket Lambda_

Voila, you no longer need the SNS and it still works the same way.

Am I missing something (could be totally wrong above of course)? Is the SNS here necessary? Does it provide any additional value over this alternative method that I've described which would simplify the design?

Other than that - great work. Thanks for providing this excellent blueprint!

**Comment by ctodd** [comment]
Tomaz, check out the Readme under Architecture. I just happened to read this myself and was wondering the same thing. :-)

[Amazon SNS]: Used to decouple streaming calls between API Gateway and Bedrock because streaming responses can take over 30 seconds in total, exceeding the limitations of HTTP integration (See [quota](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html)).

**Comment by statefb** [comment]
@tomaszdudek7 
Thank you for your suggestion. We re-verified the behavior of http integration and confirmed that lambda can continue to send message to websocket connection after 30 sec passed although the message `Endpoint request timed out` sent. So I believe that we can simplify the architecture with front-end implementation which ignore the message saying timed out. We'll modify when we have time (PR is also welcome), thank you!

**Comment by tomaszdudek7** [comment]
@ctodd Yes, but my point was that SNS is not even required here, as confirmed in the comment above.
