### ISSUE TITLE
Could not resolve the foundation model from the provided model identifier

### ISSUE THREAD

**Issue by ctodd** [aws-samples/bedrock-claude-chat#91]
When sending a chat message the frontend hangs forever. Looking at the CloudWatch BedrockChatStack-WebSocketHandler log stream, I see the following:

Failed to invoke bedrock: An error occurred (ResourceNotFoundException) when calling the InvokeModelWithResponseStream operation: Could not resolve the foundation model from the provided model identifier.

In the log stream request I see "model":"claude-v2", however digging into the backend bedrock.py I see get_model_id() is providing the correct modelID (in theory) before calling invoke. I looked at the docs and Bedrock in the console and the model identifiers do not appear to have changed (other than the addition of Claude v2.1).

I would also note I've had all models enabled in Bedrock for some time, and the app was deployed in the same region (us-west-2).

I haven't had time to dig in any further. It would be nice to add CloudWatch logging to bedrock.py as well as improve exception handling on the front end by passing the error message.

The install otherwise went as advertised.

**Comment by statefb** [comment]
Cloud you check again that claude is available on us-west-2 region? Please note that model access is set independently for each region.

**Comment by ctodd** [comment]
I can confirm that all Anthropic models have been enabled in us-west-2. I discovered that I had not set my bedrockRegion to us-west-2 in the cdk.json, so I deleted all the resources and redeployed, however the same issue persists. Looking in CloudFormation, the bedrockRegion still points to us-east-1. Is there something else I need to do after modifying the cdk.json and redeploying? For the interim, I've just enabled Bedrock access in us-east-1 and it's working.

**Comment by statefb** [comment]
To investigate the issue, I tried to invoke bedrock on us-west-2 by configuring bedrockRegion on cdk.json but I was not able to reproduce the problem and working correctly. Please make sure that you enable both `Claude` and `Claude Instant` on Model access screen on us-west-2.

**Comment by josephedward** [comment]
I have also experienced this behavior; the inability to access any Claude versions in us-west-2. I have double checked the region and model id, and the model access page, everything looks like I should be able to access. I have successfully queried Claude in the AWS console. 

I have rewritten some of your code to use Titan as the prompting model over websockets, and that worked, but most of your code assumes the conventions used by Claude, and will require some rework on my part to get additional components working. Any chance you might expand to cover more FMs supported by Bedrock?

**Comment by josephedward** [comment]
*Update:* 

I found out for certain with: 

```
import inspect
print("client : ", inspect.getmembers(client))
```

It is hardcoded at line 10 of **utils.py**:

`BEDROCK_REGION = os.environ.get("BEDROCK_REGION", "us-east-1")`

but I couldn't get to work until I hardcoded it in this method @ line 50: 

```
def get_bedrock_client():
    client = boto3.client("bedrock-runtime", BEDROCK_REGION)
    return client
```

I also added `
boto3.setup_default_session(region_name="us-west-2")` to the websocket.py handler to try to set boto3 up in the lambda session in the correct region, but have not verified if that helped. 

@statefb should I submit up a PR to test and make sure that parameter is being set programmatically? 🤔

**Comment by jaredmcqueen** [comment]
for what it's worth I tried to deploy with `us-east-1` and the chat hung forever too.  I was opted into all models.  I suspect there is a hardcoded value or an incorrect env var gets set during deployment.

**Comment by statefb** [comment]
@josephedward Sorry for late reply.

For now I can't imagine the cause of this problem.
When use bedrock client, `get_bedrock_client` is called every time (no exception). In addition to that, the env value is set at deploy time as described in CDK codes like websocket.ts and api.ts.

I'd be appreciate if you could investigate the cause of this issue. Thank you!

**Comment by statefb** [comment]
@josephedward I was unable to reproduce the phenomenon when I tried, so I couldn't test it, but indeed, due to the default session being set implicitly, the approach of explicitly creating the client at the app level when creating the client seemed like a good idea. I'll close this issue with the merge. Thank you again for your contribution!
