### ISSUE TITLE
Does deployment require Docker?

### ISSUE THREAD

**Issue by macamhi** [aws-samples/bedrock-claude-chat#94]
Thank you very much for contributing this!
But when trying to deploy with cdk deploy, whether from my PC or CloudShell, I ran into an error indicating "Cannot connect to the Docker daemon".
Is Docker really required for deployment? Or any guideline to bypass this?

**Comment by statefb** [comment]
Yes, CDK requires docker for building process.
See: https://aws.amazon.com/jp/blogs/devops/building-apps-with-aws-cdk/

**Comment by macamhi** [comment]
We will be investigating how to remove this dependency, as it makes it complicated to reuse in some corporate environments. If we succeed, would you be open to a contribution?

**Comment by statefb** [comment]
It would be hard trial to remove docker dependency. We strongly recommend to prepare specific environment for cdk build such as CodeBuild, which is used for [super-easy-deployment](https://github.com/aws-samples/bedrock-claude-chat#-super-easy-deployment).

**Comment by macamhi** [comment]
Indeed, we managed through updates to the CodeBuild stack, thanks!
