### ISSUE TITLE
[Feature Request] Download conversations for use case discovery

### ISSUE THREAD

**Issue by icoxfog417** [aws-samples/bedrock-claude-chat#96]
As a leader who is proceeding with generative AI usage in a company, I would like to discover major use cases from conversations with active users.

For example, I can detect major use case by counting keywords in prompts (such as "please summarize", "please translate", etc). In addition, I could identify heavy users by analyzing frequency. Interviewing them would be the the first step to implement an internal prompt guide or specialized application for their business. We can find sample implementations from [generative-ai-use-cases-jp](https://github.com/aws-samples/generative-ai-use-cases-jp).

As a minimum feature, downloading all the conversation data with the following items will be sufficient (bracket item is optional).

* user id
* date
* inputted prompt
* model name
* outputted prompt
* (instruction)
* (hyper parameter)

**Comment by statefb** [comment]
We're going to implement admin console functionality including downloading all conversation.

**Comment by statefb** [comment]
@icoxfog417 まだ荒削りではありますが、[こちらのリリース](https://github.com/aws-samples/bedrock-claude-chat/releases/tag/v0.4.5)で対応したため一旦closeさせていただきますmm
